(function(){
'use strict';
var charts={};
function $(id){return document.getElementById(id)}
function money(v){return 'Rp '+(Number(v)||0).toLocaleString('id-ID')}
function compact(v){v=Number(v)||0;if(Math.abs(v)>=1e9)return 'Rp '+(v/1e9).toFixed(1).replace('.0','')+' M';if(Math.abs(v)>=1e6)return 'Rp '+(v/1e6).toFixed(1).replace('.0','')+' Jt';if(Math.abs(v)>=1e3)return 'Rp '+Math.round(v/1e3)+' Rb';return money(v)}
function num(id){var n=$(id);return n?Number(String(n.textContent||'').replace(/[^0-9-]/g,''))||0:0}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function api(name,args){return new Promise(function(resolve){if(typeof window.callApi!=='function')return resolve(null);window.callApi(name,args||[],resolve,function(){resolve(null)})})}
function range(days){var e=new Date(),s=new Date();s.setDate(e.getDate()-days+1);function f(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}return{start:f(s),end:f(e)}}
function css(){if($('dash-v2-css'))return;var s=document.createElement('style');s.id='dash-v2-css';s.textContent=`
#page-dashboard{--d-blue:#1e6f9c;--d-navy:#153754;--d-green:#10b981;--d-rose:#f43f5e;--d-amber:#f59e0b}
.dash-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:1.45fr .55fr;gap:22px;padding:26px;margin-bottom:18px;border-radius:24px;background:linear-gradient(135deg,#153754,#1e6f9c 60%,#168aad);color:#fff;box-shadow:0 18px 44px rgba(21,55,84,.18)}
.dash-hero:after{content:"";position:absolute;width:260px;height:260px;right:-100px;top:-130px;border-radius:50%;background:rgba(255,255,255,.08)}.dash-hero>*{position:relative;z-index:1}
.dash-eyebrow{display:inline-flex;align-items:center;gap:7px;padding:6px 10px;border:1px solid rgba(255,255,255,.2);border-radius:999px;background:rgba(255,255,255,.1);font-size:10px;font-weight:800;letter-spacing:.6px;text-transform:uppercase}
.dash-hero h2{margin:13px 0 7px;font-size:clamp(23px,3vw,34px);letter-spacing:-.7px}.dash-hero p{max-width:720px;color:rgba(255,255,255,.78);font-size:13px;line-height:1.65}
.dash-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:17px}.dash-chip{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border-radius:12px;background:rgba(255,255,255,.11);font-size:11px;font-weight:600}
.dash-health{height:100%;padding:18px;border:1px solid rgba(255,255,255,.16);border-radius:18px;background:rgba(255,255,255,.1);backdrop-filter:blur(10px)}.dash-health-head{display:flex;justify-content:space-between;font-size:11px;font-weight:700}.dash-score{font-size:31px;font-weight:800;margin-top:12px}.dash-health p{font-size:10px;margin:2px 0 0}.dash-bar{height:8px;margin:14px 0 10px;border-radius:999px;background:rgba(255,255,255,.15);overflow:hidden}.dash-bar span{display:block;height:100%;width:0;background:linear-gradient(90deg,#6ee7b7,#fde68a);border-radius:inherit;transition:.45s}
#page-dashboard .stats-grid{gap:14px;margin-bottom:18px}#page-dashboard .stat-card{position:relative;overflow:hidden;align-items:flex-start;text-align:left;min-height:148px;padding:18px;border:1px solid #e5edf4;border-radius:18px;box-shadow:0 9px 24px rgba(15,23,42,.055);transition:.2s}#page-dashboard .stat-card:hover{transform:translateY(-3px);box-shadow:0 15px 32px rgba(15,23,42,.09)}
#page-dashboard .stat-card:after{content:"";position:absolute;width:90px;height:90px;right:-38px;top:-38px;border-radius:50%;background:rgba(30,111,156,.08)}#page-dashboard .stat-card:nth-child(2):after{background:rgba(16,185,129,.1)}#page-dashboard .stat-card:nth-child(3):after{background:rgba(244,63,94,.1)}#page-dashboard .stat-card:nth-child(4):after{background:rgba(245,158,11,.12)}
#page-dashboard .stat-icon{width:44px;height:44px;min-width:44px;border-radius:14px;margin-bottom:17px}#page-dashboard .stat-info{width:100%}#page-dashboard .stat-value{font-size:clamp(19px,2vw,25px);font-weight:800;color:#172b3a;letter-spacing:-.5px}#page-dashboard .stat-label{margin-top:5px;font-size:12px;font-weight:700;color:#526577}#page-dashboard .stat-trend{margin-top:9px;font-size:10px}
.dash-grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,.85fr);gap:16px;margin-bottom:16px}.dash-grid.equal{grid-template-columns:repeat(2,minmax(0,1fr))}.dash-panel{min-width:0;background:#fff;border:1px solid #e4edf4;border-radius:20px;box-shadow:0 10px 28px rgba(15,23,42,.05)}
.dash-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:18px 18px 0}.dash-title{display:flex;align-items:center;gap:11px}.dash-icon{width:38px;height:38px;display:flex;align-items:center;justify-content:center;border-radius:12px;background:#eaf5fb;color:#1e6f9c}.dash-panel h3{font-size:14px;color:#1d3344;margin:0}.dash-desc{font-size:10px;color:#7b8d9b;margin-top:3px}.dash-body{padding:12px 18px 18px}.dash-chart{height:285px;position:relative}.dash-filter{padding:7px 9px;border:1px solid #d9e5ee;border-radius:10px;background:#fff;color:#42586b;font-size:10px;font-weight:700}
.dash-insights{display:grid;gap:10px}.dash-insight{display:flex;gap:11px;padding:12px;border:1px solid #edf2f6;border-radius:14px;background:#f7fafc}.dash-insight i{width:34px;height:34px;display:flex;align-items:center;justify-content:center;border-radius:11px}.dash-insight strong{display:block;font-size:11px;color:#243b4d;margin-bottom:3px}.dash-insight span{display:block;font-size:10px;line-height:1.45;color:#718394}
.dash-sppg{display:grid;gap:10px}.dash-sppg-row{display:grid;grid-template-columns:minmax(90px,1fr) minmax(100px,1.25fr) auto;gap:11px;align-items:center}.dash-sppg-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;font-weight:700;color:#334b5e}.dash-track{height:7px;background:#edf3f7;border-radius:999px;overflow:hidden}.dash-track span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#38bdf8,#1e6f9c)}.dash-val{font-size:10px;font-weight:800;color:#1e425c}.dash-empty{display:grid;place-items:center;min-height:210px;text-align:center;color:#8293a2}.dash-empty i{font-size:27px;color:#bdd0dc;margin-bottom:8px}.dash-empty strong{display:block;font-size:11px}
@media(max-width:980px){.dash-hero,.dash-grid,.dash-grid.equal{grid-template-columns:1fr}}@media(max-width:640px){.dash-hero{padding:20px;border-radius:20px}.dash-health{display:none}#page-dashboard .stats-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));overflow:visible}#page-dashboard .stat-card{min-width:0;min-height:136px;padding:14px}#page-dashboard .stat-value{font-size:17px}.dash-chart{height:245px}.dash-head{padding:15px 15px 0}.dash-body{padding:10px 15px 15px}}
`;document.head.appendChild(s)}
function hero(){return `<section class="dash-hero"><div><span class="dash-eyebrow"><i class="fas fa-chart-line"></i> Ringkasan operasional</span><h2 id="dashGreeting">Selamat datang di SIM-SPPG</h2><p>Pantau arus kas, transaksi yang memerlukan perhatian, dan performa setiap unit SPPG dalam satu tampilan.</p><div class="dash-meta"><span class="dash-chip"><i class="fas fa-building"></i><span id="dashSppg">Semua SPPG</span></span><span class="dash-chip"><i class="fas fa-user-shield"></i><span id="dashRole">Pengguna</span></span><span class="dash-chip"><i class="fas fa-calendar-day"></i><span id="dashDate">-</span></span></div></div><div class="dash-health"><div class="dash-health-head"><span>Kesehatan anggaran</span><i class="fas fa-shield-alt"></i></div><div class="dash-score" id="dashScore">0%</div><p id="dashHealthText">Menunggu data transaksi</p><div class="dash-bar"><span id="dashBar"></span></div><p>Rasio saldo terhadap total pemasukan.</p></div></section>`}
function panels(){return `<div id="dashPanels"><div class="dash-grid"><section class="dash-panel"><div class="dash-head"><div class="dash-title"><div class="dash-icon"><i class="fas fa-chart-area"></i></div><div><h3>Tren arus kas</h3><div class="dash-desc">Pemasukan, pengeluaran, dan saldo harian</div></div></div><select id="dashPeriod" class="dash-filter"><option value="7">7 hari</option><option value="30" selected>30 hari</option><option value="90">90 hari</option></select></div><div class="dash-body"><div class="dash-chart"><canvas id="dashCashflow"></canvas></div></div></section><section class="dash-panel"><div class="dash-head"><div class="dash-title"><div class="dash-icon"><i class="fas fa-lightbulb"></i></div><div><h3>Insight hari ini</h3><div class="dash-desc">Sorotan otomatis operasional</div></div></div></div><div class="dash-body"><div id="dashInsights" class="dash-insights"></div></div></section></div><div class="dash-grid equal"><section class="dash-panel"><div class="dash-head"><div class="dash-title"><div class="dash-icon"><i class="fas fa-chart-pie"></i></div><div><h3>Komposisi transaksi</h3><div class="dash-desc">Porsi pemasukan dan pengeluaran</div></div></div></div><div class="dash-body"><div class="dash-chart"><canvas id="dashComposition"></canvas></div></div></section><section class="dash-panel"><div class="dash-head"><div class="dash-title"><div class="dash-icon"><i class="fas fa-building"></i></div><div><h3>Pengeluaran per SPPG</h3><div class="dash-desc">Unit dengan pengeluaran terbesar</div></div></div></div><div class="dash-body"><div id="dashSppgList" class="dash-sppg"></div></div></section></div></div>`}
function identity(){var u=window.currentUser||{},h=new Date().getHours(),g=h<11?'Selamat pagi':h<15?'Selamat siang':h<19?'Selamat sore':'Selamat malam';if($('dashGreeting'))$('dashGreeting').textContent=g+(u.namaLengkap?', '+u.namaLengkap.split(' ')[0]:'')+'.';if($('dashSppg'))$('dashSppg').textContent=u.role==='SUPER_ADMIN'?'Seluruh SPPG':(u.sppg||'SPPG belum ditentukan');if($('dashRole'))$('dashRole').textContent=String(u.role||u.jabatan||'Pengguna').replace(/_/g,' ');if($('dashDate'))$('dashDate').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
function health(){var inc=num('statPemasukan'),bal=num('statSaldo'),score=inc?Math.max(0,Math.min(100,Math.round(bal/inc*100))):0;if($('dashScore'))$('dashScore').textContent=score+'%';if($('dashBar'))$('dashBar').style.width=score+'%';if($('dashHealthText'))$('dashHealthText').textContent=score>=50?'Kondisi anggaran sehat':score>=20?'Perlu pengendalian belanja':inc?'Saldo perlu perhatian':'Menunggu data transaksi'}
function empty(canvas,msg){if(!canvas)return;canvas.style.display='none';canvas.parentElement.innerHTML='<div class="dash-empty"><div><i class="fas fa-chart-area"></i><strong>'+esc(msg)+'</strong></div></div>'}
function renderCharts(rows){if(!window.Chart)return;Chart.defaults.font.family='Inter, sans-serif';Chart.defaults.color='#708293';var c=$('dashCashflow');if(charts.cash)charts.cash.destroy();if(!rows.length)empty(c,'Belum ada data tren pada periode ini.');else charts.cash=new Chart(c,{type:'line',data:{labels:rows.map(r=>r.tanggal),datasets:[{label:'Pemasukan',data:rows.map(r=>+r.pemasukan||0),borderColor:'#10b981',backgroundColor:'rgba(16,185,129,.08)',fill:true,tension:.35,borderWidth:2,pointRadius:2},{label:'Pengeluaran',data:rows.map(r=>+r.pengeluaran||0),borderColor:'#f43f5e',backgroundColor:'rgba(244,63,94,.06)',fill:true,tension:.35,borderWidth:2,pointRadius:2},{label:'Saldo',data:rows.map(r=>+r.saldo||0),borderColor:'#1e6f9c',tension:.35,borderWidth:2.5,pointRadius:1,borderDash:[5,4]}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{tooltip:{callbacks:{label:c=>c.dataset.label+': '+money(c.raw)}}},scales:{x:{grid:{display:false},ticks:{maxRotation:0,maxTicksLimit:7}},y:{beginAtZero:true,grid:{color:'rgba(148,163,184,.13)'},ticks:{callback:compact}}}}});var d=$('dashComposition');if(charts.comp)charts.comp.destroy();var inc=num('statPemasukan'),exp=num('statPengeluaran');if(!inc&&!exp)empty(d,'Komposisi transaksi belum tersedia.');else charts.comp=new Chart(d,{type:'doughnut',data:{labels:['Pemasukan','Pengeluaran'],datasets:[{data:[inc,exp],backgroundColor:['#10b981','#f43f5e'],borderWidth:0,hoverOffset:6}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>c.label+': '+money(c.raw)}}}}})}
function renderSppg(rows){var box=$('dashSppgList'),data=(rows||[]).slice().sort((a,b)=>(+b.pengeluaran||0)-(+a.pengeluaran||0)).slice(0,7);if(!data.length){box.innerHTML='<div class="dash-empty"><div><i class="fas fa-building"></i><strong>Data per SPPG belum tersedia.</strong></div></div>';return}var max=Math.max.apply(null,data.map(r=>+r.pengeluaran||0))||1;box.innerHTML=data.map(r=>`<div class="dash-sppg-row"><div class="dash-sppg-name" title="${esc(r.name)}">${esc(r.name)}</div><div class="dash-track"><span style="width:${Math.max(3,Math.round((+r.pengeluaran||0)/max*100))}%"></span></div><div class="dash-val">${compact(r.pengeluaran)}</div></div>`).join('')}
function insights(rows,sppg){var box=$('dashInsights'),queue=num('statAntrian'),pending=num('statAntrianNominal'),last=rows[rows.length-1],top=(sppg||[]).slice().sort((a,b)=>(+b.pengeluaran||0)-(+a.pengeluaran||0))[0],items=[['fa-hourglass-half','#fff7ed','#c2410c',queue+' transaksi menunggu approval',pending?'Nominal tertunda '+money(pending)+'.':'Tidak ada nominal tertunda.'],['fa-calendar-check','#ecfdf5','#047857',last?'Aktivitas terakhir '+last.tanggal:'Belum ada aktivitas harian',last?'Pemasukan '+money(last.pemasukan)+' dan pengeluaran '+money(last.pengeluaran)+'.':'Data muncul setelah transaksi tercatat.'],['fa-building','#eff6ff','#1d4ed8',top?top.name+' tertinggi':'Perbandingan SPPG belum tersedia',top?'Pengeluaran tercatat '+money(top.pengeluaran)+'.':'Data unit belum tersedia.'],['fa-shield-alt','#f5f3ff','#6d28d9','Kontrol pengeluaran','Pastikan bukti transaksi dan approval selalu lengkap.']];box.innerHTML=items.map(i=>`<div class="dash-insight"><i class="fas ${i[0]}" style="background:${i[1]};color:${i[2]}"></i><div><strong>${esc(i[3])}</strong><span>${esc(i[4])}</span></div></div>`).join('')}
var loading=false,lastLoad=0;async function load(force){if(loading||!window.currentUser||(!force&&Date.now()-lastLoad<30000))return;loading=true;var days=+$('dashPeriod').value||30,r=range(days),res=await Promise.all([api('getChartData',[{dateStart:r.start,dateEnd:r.end}]),api('getSPPGData',[r.start,r.end])]),rows=Array.isArray(res[0])?res[0]:[],sppg=Array.isArray(res[1])?res[1]:[];renderCharts(rows);renderSppg(sppg);insights(rows,sppg);identity();health();lastLoad=Date.now();loading=false}
function init(){var page=$('page-dashboard'),stats=$('dashboardStats'),quick=$('quickAccessSection');if(!page||!stats||!quick)return setTimeout(init,300);if($('dashPanels'))return;css();stats.insertAdjacentHTML('beforebegin',hero());quick.insertAdjacentHTML('beforebegin',panels());$('dashPeriod').addEventListener('change',()=>load(true));['statSaldo','statPemasukan','statPengeluaran','statAntrian','statAntrianNominal'].forEach(id=>{var n=$(id);if(n)new MutationObserver(function(){health();if(id!=='statSaldo')setTimeout(function(){renderCharts([])},0)}).observe(n,{childList:true,subtree:true,characterData:true})});identity();health();setInterval(function(){var p=$('page-dashboard');if(p&&!p.classList.contains('hidden')&&getComputedStyle(p).display!=='none')load(false)},1400);setTimeout(()=>load(true),700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();