/* SIM-SPPG isolated UI/UX fixes. Safe to remove independently. */
(function(){
'use strict';
if(window.__SIM_SPPG_UIUX_FIX__)return;window.__SIM_SPPG_UIUX_FIX__=true;
var NOTIF_URL='https://dmjsgtichrfxhyywstrt.supabase.co/functions/v1/notifications-action';
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function installStyle(){if($('uiuxFixStyle'))return;var s=document.createElement('style');s.id='uiuxFixStyle';s.textContent='@media(min-width:769px){.desktop-add-transaction{display:inline-flex!important}}@media(max-width:768px){.desktop-add-transaction{display:none!important}}.filter-bar.collapsed .filter-grid,.filter-bar.collapsed .filter-content,.filter-bar.collapsed .filter-actions{display:none!important}.report-history-fix{margin-top:18px;background:#fff;border:1px solid var(--slate-200);border-radius:12px;padding:16px}.report-history-fix table{width:100%;border-collapse:collapse}.report-history-fix th,.report-history-fix td{padding:9px;border-bottom:1px solid var(--slate-100);font-size:12px;text-align:left}';document.head.appendChild(s)}
function addTxButton(){var p=$('page-transaksi');if(!p||p.querySelector('.desktop-add-transaction'))return;var h=p.querySelector('.page-header,.content-header,.section-header,.page-title-row')||p.firstElementChild;if(!h)return;var b=document.createElement('button');b.type='button';b.className='btn btn-primary btn-sm no-print desktop-add-transaction';b.innerHTML='<i class="fas fa-plus"></i> Tambah Transaksi';b.onclick=function(){if(typeof openAddTransaksiModal==='function')openAddTransaksiModal()};h.appendChild(b)}
function collapseFilters(){document.querySelectorAll('.filter-bar').forEach(function(bar,i){if(!bar.id)bar.id=$('page-transaksi')&&$('page-transaksi').contains(bar)?'txFilterBar':'autoFilterBar'+i;var k='filterCollapsed_'+bar.id,v=null;try{v=localStorage.getItem(k)}catch(e){}bar.classList.toggle('collapsed',v===null?true:v==='1')});window.restoreFilterBarState=function(id){var b=$(id);if(!b)return;var v=null;try{v=localStorage.getItem('filterCollapsed_'+id)}catch(e){}b.classList.toggle('collapsed',v===null?true:v==='1')}}
function notifApi(fn,params,ok){var t='';try{t=localStorage.getItem('sppg_jwt')||''}catch(e){}fetch(NOTIF_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({function:fn,parameters:params||[]})}).then(function(r){return r.json()}).then(function(j){if(j.error)throw new Error(j.error);if(ok)ok(Object.prototype.hasOwnProperty.call(j,'result')?j.result:j)}).catch(console.error)}
function installNotif(){var w=$('notifBellWrap');if(w&&window.currentUser)w.classList.remove('hidden');window.loadNotifications=function(){if(!window.currentUser)return;notifApi('getNotifications',[],function(r){if(!r||!r.success)return;window.notifList=r.data||[];if(typeof renderNotifBadge==='function')renderNotifBadge(r.unreadCount||0);if(typeof renderNotifPanel==='function')renderNotifPanel()})};window.initNotifBell=function(){var b=$('notifBellWrap');if(!b||!window.currentUser)return;b.classList.remove('hidden');loadNotifications();if(window.notifPollTimer)clearInterval(window.notifPollTimer);window.notifPollTimer=setInterval(loadNotifications,60000)};initNotifBell()}
function approveSuperAdmin(){if(!window.currentUser||window.currentUser.role!=='SUPER_ADMIN')return;var t=$('approvalTableBody');if(!t)return;t.querySelectorAll('tr[data-id]').forEach(function(r){var g=r.querySelector('.action-group');if(!g||g.querySelector('.approve'))return;var id=r.getAttribute('data-id'),b=document.createElement('button');b.className='action-btn approve';b.title='Approve';b.innerHTML='<i class="fas fa-check"></i>';b.onclick=function(){if(typeof openApprovalModal==='function')openApprovalModal(id)};g.appendChild(b)})}
function history(){var p=$('page-laporan');if(!p)return;var w=$('reportHistoryFix');if(!w){w=document.createElement('section');w.id='reportHistoryFix';w.className='report-history-fix';w.innerHTML='<h3><i class="fas fa-history"></i> Riwayat File Laporan</h3><div class="table-scroll"><table><thead><tr><th>Dibuat</th><th>Periode</th><th>Format</th><th>Jumlah</th><th>Total</th></tr></thead><tbody></tbody></table></div>';p.appendChild(w)}var rows=[];try{rows=JSON.parse(localStorage.getItem('sim_sppg_report_history_v1')||'[]')}catch(e){}w.querySelector('tbody').innerHTML=rows.length?rows.map(function(r){return'<tr><td>'+esc(new Date(r.tanggal).toLocaleString('id-ID'))+'</td><td>'+esc(r.periode||((r.periodeAwal||'-')+' s.d. '+(r.periodeAkhir||'-')))+'</td><td>'+esc(r.format||'PDF')+'</td><td>'+esc(r.jumlah||r.jumlahTransaksi||0)+'</td><td>Rp '+Number(r.total||r.totalNominal||0).toLocaleString('id-ID')+'</td></tr>'}).join(''):'<tr><td colspan="5">Belum ada laporan yang dibuat.</td></tr>'}
function install(){installStyle();addTxButton();collapseFilters();installNotif();approveSuperAdmin();history()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();new MutationObserver(function(){addTxButton();collapseFilters();approveSuperAdmin();history()}).observe(document.documentElement,{childList:true,subtree:true});
})();