import { Caller,fmt,iso,lo,s,sb,visibleActors } from './core.ts';
const AUDIT_COLUMNS='LOG_ID,TIMESTAMP,USER_EMAIL,ROLE,ACTION_TYPE,TABLE_NAME,RECORD_ID,FIELD_CHANGED,OLD_VALUE,NEW_VALUE,DESCRIPTION,STATUS';
function pageSpec(v:any){const requested=Number(v?.page)>0||Number(v?.pageSize)>0;if(!requested)return null;const page=Math.max(1,Math.floor(Number(v?.page)||1));const pageSize=Math.min(100,Math.max(1,Math.floor(Number(v?.pageSize)||25)));return{page,pageSize,from:(page-1)*pageSize,to:page*pageSize-1}}
function paged(data:any[],v:any){const x=pageSpec(v);if(!x)return null;const total=data.length;return{data:data.slice(x.from,x.to+1),page:x.page,pageSize:x.pageSize,total,hasMore:x.to+1<total}}
export async function getAuditLog(p:any[],c:Caller){
  if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Akses ditolak.');
  const f=p[0]||{},page=pageSpec(f),actors=await visibleActors(c),search=lo(f.search);
  if(actors&&!actors.size)return page?{success:true,data:[],page:page.page,pageSize:page.pageSize,total:0,hasMore:false}:{success:true,data:[]};
  let q=page&&!search?sb.from('AUDIT LOG').select(AUDIT_COLUMNS,{count:'exact'}):sb.from('AUDIT LOG').select(AUDIT_COLUMNS);
  if(actors)q=q.in('USER_EMAIL',[...actors]);
  if(f.actionType&&f.actionType!=='ALL')q=q.eq('ACTION_TYPE',s(f.actionType));
  const start=iso(f.dateStart),end=iso(f.dateEnd);
  if(start)q=q.gte('TIMESTAMP',`${start}T00:00:00`);
  if(end)q=q.lt('TIMESTAMP',`${end}T23:59:59.999999`);
  q=q.order('TIMESTAMP',{ascending:false});
  // Search spans several columns and stays local; normal page requests are ranged
  // in PostgREST so hundreds of audit rows are not transferred per click.
  if(page&&!search)q=q.range(page.from,page.to);else q=q.limit(500);
  const result=await q;if(result.error)throw result.error;
  let rows=result.data||[];
  if(search)rows=rows.filter((x:any)=>lo(`${x.USER_EMAIL} ${x.ACTION_TYPE} ${x.TABLE_NAME} ${x.RECORD_ID} ${x.DESCRIPTION}`).includes(search));
  const data=rows.map((x:any)=>({uuid:x.LOG_ID||'',waktu:fmt(x.TIMESTAMP),pelaku:x.USER_EMAIL||'-',role:x.ROLE||'-',actionType:x.ACTION_TYPE||'-',tableName:x.TABLE_NAME||'-',recordId:x.RECORD_ID||'-',fieldChanged:x.FIELD_CHANGED||'-',oldValue:x.OLD_VALUE||'',newValue:x.NEW_VALUE||'',deskripsi:x.DESCRIPTION||'',status:x.STATUS||'SUCCESS'}));
  if(page&&!search){const total=result.count??data.length;return{success:true,data,page:page.page,pageSize:page.pageSize,total,hasMore:page.to+1<total}}
  const pg=paged(data,f);return pg?{success:true,...pg}:{success:true,data};
}
export async function getNotifications(p:any[],c:Caller){/* Notifications render only seven audit fields; exclude verbose old/new payloads. */const q=await sb.from('AUDIT LOG').select('LOG_ID,TIMESTAMP,USER_EMAIL,ACTION_TYPE,TABLE_NAME,RECORD_ID,DESCRIPTION').in('ACTION_TYPE',['ADD','EDIT','DELETE']).in('TABLE_NAME',['USERS','TRANSAKSI','MASTER_BB','MASTER_SUPPLIER','SURVEI_BB','SERAH_TERIMA','MENU_HARIAN']).order('TIMESTAMP',{ascending:false}).limit(50);if(q.error)throw q.error;let rows=q.data||[];const actors=await visibleActors(c);if(actors)rows=rows.filter((x:any)=>actors.has(lo(x.USER_EMAIL)));const ids=rows.map((x:any)=>x.LOG_ID).filter(Boolean);let read=new Set<string>();if(ids.length){const q2=await sb.from('NOTIFICATION_READS').select('log_id').eq('admin_email',c.email).in('log_id',ids);if(q2.error)throw q2.error;read=new Set((q2.data||[]).map((x:any)=>s(x.log_id)))}const meta:any={USERS:['users','fa-user-plus','Pendaftar'],TRANSAKSI:['transaksi','fa-exchange-alt','Transaksi'],MASTER_BB:['master-bahan','fa-boxes','Bahan Baku'],MASTER_SUPPLIER:['master-supplier','fa-truck','Supplier'],SURVEI_BB:['survei','fa-search-dollar','Survei'],SERAH_TERIMA:['serah-terima','fa-dolly','Serah Terima'],MENU_HARIAN:['menu-mbg','fa-utensils','Menu MBG']};const allData=rows.map((x:any)=>{const m=meta[x.TABLE_NAME]||['dashboard','fa-bell','Aktivitas'],a=s(x.ACTION_TYPE),suffix=a==='ADD'?'Baru':a==='EDIT'?'Diedit':'Dihapus';return{logId:x.LOG_ID,page:m[0],icon:a==='EDIT'?'fa-pen':a==='DELETE'?'fa-trash-alt':m[1],label:`${m[2]} ${suffix}`,actionType:a,recordId:x.RECORD_ID||'',pelaku:x.USER_EMAIL||'-',deskripsi:x.DESCRIPTION||'',waktu:fmt(x.TIMESTAMP),waktuRaw:x.TIMESTAMP||'',isRead:read.has(s(x.LOG_ID))}});const opt=p[0]||{},pg=paged(allData,opt),data=pg?pg.data:allData;return pg?{success:true,...pg,unreadCount:allData.filter((x:any)=>!x.isRead).length}:{success:true,data,unreadCount:data.filter((x:any)=>!x.isRead).length}}
export async function markNotificationRead(p:any[],c:Caller){const logId=s(p[0]);if(!logId)throw new Error('ID notifikasi wajib tersedia.');const existing=await sb.from('NOTIFICATION_READS').select('id').eq('admin_email',c.email).eq('log_id',logId).maybeSingle();if(existing.error)throw existing.error;if(!existing.data){const q=await sb.from('NOTIFICATION_READS').insert({admin_email:c.email,log_id:logId,read_at:new Date().toISOString()});if(q.error)throw q.error}return{success:true,message:'Notifikasi ditandai sudah dibaca.'}}
export async function markAllNotificationsRead(_p:any[],c:Caller){const q=await sb.from('AUDIT LOG').select('LOG_ID,USER_EMAIL').in('ACTION_TYPE',['ADD','EDIT','DELETE']).in('TABLE_NAME',['USERS','TRANSAKSI','MASTER_BB','MASTER_SUPPLIER','SURVEI_BB','SERAH_TERIMA','MENU_HARIAN']).order('TIMESTAMP',{ascending:false}).limit(50);if(q.error)throw q.error;let rows=q.data||[];const actors=await visibleActors(c);if(actors)rows=rows.filter((x:any)=>actors.has(lo(x.USER_EMAIL)));const ids=rows.map((x:any)=>s(x.LOG_ID)).filter(Boolean);if(!ids.length)return{success:true,message:'Tidak ada notifikasi untuk ditandai.'};const current=await sb.from('NOTIFICATION_READS').select('log_id').eq('admin_email',c.email).in('log_id',ids);if(current.error)throw current.error;const existing=new Set((current.data||[]).map((x:any)=>s(x.log_id)));const insertRows=ids.filter((id:string)=>!existing.has(id)).map((id:string)=>({admin_email:c.email,log_id:id,read_at:new Date().toISOString()}));if(insertRows.length){const ins=await sb.from('NOTIFICATION_READS').insert(insertRows);if(ins.error)throw ins.error}return{success:true,message:'Semua notifikasi ditandai sudah dibaca.',count:ids.length}}
