import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';
export const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
export const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
export const s=(v:unknown)=>String(v??'').trim();
export const lo=(v:unknown)=>s(v).toLowerCase();
export const norm=(v:unknown)=>s(v).replace(/\s+/g,' ').toUpperCase();
export const fmt=(v:unknown)=>{const x=s(v);if(!x)return '-';const d=new Date(x);if(Number.isNaN(d.getTime()))return x;return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`};
export const iso=(v:unknown)=>{const x=s(v);if(!x)return '';if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);const m=x.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:x};
export const paymentStatus=(v:unknown)=>{const x=s(v).toUpperCase().replace(/\s+/g,'_');return x==='LUNAS'?'SUDAH_DIBAYAR':(x||'BELUM_BAYAR')};
export type Caller={id:string,email:string,username:string,role:string};
export type Assignment={sppg:string,yayasan:string,sppgKey:string,yayasanKey:string};
export async function getCaller(req:Request):Promise<Caller>{const h=req.headers.get('Authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)throw new Error('Token tidak ditemukan.');const auth=await sb.auth.getUser(token);if(auth.error||!auth.data.user)throw new Error('Token tidak valid atau kedaluwarsa.');const q=await sb.from('USERS').select('ID,EMAIL,USERNAME,ROLE').eq('ID',auth.data.user.id).maybeSingle();if(q.error||!q.data)throw new Error('Profil user tidak ditemukan.');return{id:auth.data.user.id,email:lo(auth.data.user.email||q.data.EMAIL),username:lo(q.data.USERNAME),role:norm(q.data.ROLE)}}
export async function getAssignments(c:Caller):Promise<Assignment[]>{if(c.role!=='ADMIN')return[];const q=await sb.from('ADMIN_ASSIGNMENT').select('sppg,yayasan,admin_email');if(q.error)throw q.error;const seen=new Set<string>(),out:Assignment[]=[];for(const x of q.data||[]){if(lo(x.admin_email)!==c.email)continue;const sppg=s(x.sppg),yayasan=s(x.yayasan),sppgKey=norm(sppg),yayasanKey=norm(yayasan),key=`${sppgKey}::${yayasanKey}`;if(!sppgKey||!yayasanKey||seen.has(key))continue;seen.add(key);out.push({sppg,yayasan,sppgKey,yayasanKey})}return out}
export function assignmentMatches(a:Assignment[],row:any){const sppgKey=norm(row?.SPPG),yayasanKey=norm(row?.YAYASAN);return a.some(x=>x.sppgKey===sppgKey&&x.yayasanKey===yayasanKey)}
export async function visibleTransactions(c:Caller){const q=await sb.from('TRANSAKSI').select('*').order('Tanggal',{ascending:true});if(q.error)throw q.error;const rows=q.data||[];if(c.role==='SUPER_ADMIN')return rows;if(c.role==='ADMIN'){const a=await getAssignments(c);return rows.filter((r:any)=>assignmentMatches(a,r))}return rows.filter((r:any)=>{const owner=lo(r.User);return owner===c.email||owner===c.username})}
export async function visibleActors(c:Caller){if(c.role==='SUPER_ADMIN')return null;if(c.role==='ADMIN'){const a=await getAssignments(c);const q=await sb.from('USERS').select('EMAIL,USERNAME,SPPG,"NAMA YAYASAN"');if(q.error)throw q.error;return new Set((q.data||[]).filter((u:any)=>assignmentMatches(a,{SPPG:u.SPPG,YAYASAN:u['NAMA YAYASAN']})).flatMap((u:any)=>[lo(u.EMAIL),lo(u.USERNAME)]).filter(Boolean))}return new Set([c.email,c.username].filter(Boolean))}
