import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';

const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const T={U:'USERS',X:'TRANSAKSI',A:'ADMIN_ASSIGNMENT',P:'TRANSAKSI_PAYMENT_PROOFS',D:'TRANSAKSI_DOCUMENTS',L:'AUDIT LOG'};
const B={foto:'transaksi-images',file:'transaksi-files',ttdUser:'paraf-user',nota:'nota-pembelian',ttdVerif:'paraf-verifikator',payment:'bukti-payment'};
const DT={foto:'FOTO_TRANSAKSI',file:'FILE_TRANSAKSI',ttdUser:'TTD_USER',nota:'NOTA_PEMBELIAN',ttdVerif:'TTD_VERIFIKATOR_LEGACY',approval:'BUKTI_APPROVAL_LEGACY'};
type Caller={id:string,email:string,role:string,sppg:string,yayasan:string,nama:string};
type Doc={transaksi_id:string,document_type:string,storage_bucket:string,storage_path:string,mime_type?:string|null,original_file_name?:string|null,created_at?:string,updated_at?:string};
const j=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}});
const s=(v:unknown)=>String(v??'').trim();
const lo=(v:unknown)=>s(v).toLowerCase();
const status=(v:unknown)=>{const x=s(v).toUpperCase().replace(/\s+/g,'_');return x==='LUNAS'?'SUDAH_DIBAYAR':(x||'BELUM_BAYAR')};
const valid=(v:unknown)=>{const x=s(v);return !!x&&x!=='-'&&!/^(FOTO|FILE)$/i.test(x)};
const date=(v:unknown)=>{const x=s(v);if(!x)return new Date().toISOString().slice(0,10);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);const m=x.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:x};
function bytes(v:string){const raw=v.includes(',')?v.split(',').pop()!:v;const bin=atob(raw);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function docIndex(rows:Doc[]){const m=new Map<string,Doc>();for(const r of rows||[]){const old=m.get(r.document_type);if(!old||s(r.updated_at||r.created_at)>=s(old.updated_at||old.created_at))m.set(r.document_type,r)}return m}
const dp=(m:Map<string,Doc>,type:string)=>s(m.get(type)?.storage_path);
const missingDocs=(m:Map<string,Doc>)=>{const miss=[] as string[];if(!valid(dp(m,DT.foto))&&!valid(dp(m,DT.file)))miss.push('Bukti Transaksi');if(!valid(dp(m,DT.ttdUser)))miss.push('TTD User');if(!valid(dp(m,DT.nota)))miss.push('Nota Pembelian');return miss};
const docStatus=(m:Map<string,Doc>)=>{const miss=missingDocs(m);return miss.length?`Dokumen Tidak Lengkap: ${miss.join(', ')}`:'Dokumen Lengkap'};
const legacyDocs=(r:any)=>docIndex([
  valid(r['UPLOUD FOTO'])?{transaksi_id:r.ID,document_type:DT.foto,storage_bucket:B.foto,storage_path:s(r['UPLOUD FOTO'])}:null,
  valid(r['UPLOUD FILE'])?{transaksi_id:r.ID,document_type:DT.file,storage_bucket:B.file,storage_path:s(r['UPLOUD FILE'])}:null,
  valid(r['TTD USER'])?{transaksi_id:r.ID,document_type:DT.ttdUser,storage_bucket:B.ttdUser,storage_path:s(r['TTD USER'])}:null,
  valid(r['NOTA PEMBELIAN'])?{transaksi_id:r.ID,document_type:DT.nota,storage_bucket:B.nota,storage_path:s(r['NOTA PEMBELIAN'])}:null,
  valid(r['TTD VERIFIKATOR'])?{transaksi_id:r.ID,document_type:DT.ttdVerif,storage_bucket:B.ttdVerif,storage_path:s(r['TTD VERIFIKATOR'])}:null,
  valid(r['LINK FOTO/ FILE  BUKTI TRANSAKSI'])?{transaksi_id:r.ID,document_type:DT.approval,storage_bucket:B.payment,storage_path:s(r['LINK FOTO/ FILE  BUKTI TRANSAKSI'])}:null
].filter(Boolean) as Doc[]);
function map(r:any,d:Map<string,Doc>){return{id:r.ID||'',kode:r['Kode Pemasukan']||'',tanggal:r.Tanggal||'',kategori:r.Kategori||'',jenisKategori:r['Jenis Kategori']||'',sppg:r.SPPG||'',yayasan:r.YAYASAN||'',nominal:Number(r.Nominal)||0,uploadFoto:dp(d,DT.foto),uploadFile:dp(d,DT.file),catatan:r.Catatan||'',user:r.User||'',item:r['Nama Item/ Bahan Baku']||'',namaItem:r['Nama Item/ Bahan Baku']||'',metodeTransaksi:status(r['Metode Transaksi']),ttdVerifikator:dp(d,DT.ttdVerif),ttdUser:dp(d,DT.ttdUser),notaPembelian:dp(d,DT.nota),approvedBy:r['APPROVED BY']||'',waktuApprove:r['WAKTU APPROVE']||'',statusDokumen:docStatus(d),catatanApproval:r['Catatan Approval']||r.Catatan_1||''}}
async function docsFor(ids:string[]){const out=new Map<string,Map<string,Doc>>();const uniq=[...new Set(ids.filter(Boolean))];if(!uniq.length)return out;const q=await sb.from(T.D).select('*').in('transaksi_id',uniq).order('updated_at',{ascending:true});if(q.error)throw q.error;for(const r of q.data||[]){const id=s(r.transaksi_id);if(!out.has(id))out.set(id,new Map());out.get(id)!.set(s(r.document_type),r as Doc)}return out}
async function caller(req:Request):Promise<Caller>{const h=req.headers.get('Authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)throw new Error('Token tidak ditemukan.');const {data,error}=await sb.auth.getUser(token);if(error||!data.user)throw new Error('Token tidak valid atau kedaluwarsa.');const q=await sb.from(T.U).select('ID,EMAIL,ROLE,SPPG,"NAMA YAYASAN","NAMA LENGKAP"').eq('ID',data.user.id).maybeSingle();if(q.error||!q.data)throw new Error('Profil user tidak ditemukan.');return{id:data.user.id,email:lo(data.user.email||q.data.EMAIL),role:s(q.data.ROLE).toUpperCase(),sppg:s(q.data.SPPG),yayasan:s(q.data['NAMA YAYASAN']),nama:s(q.data['NAMA LENGKAP'])}}
async function pairs(c:Caller){if(c.role!=='ADMIN')return[];const q=await sb.from(T.A).select('sppg,yayasan').eq('admin_email',c.email);if(q.error)throw q.error;return(q.data||[]).map((r:any)=>[s(r.sppg),s(r.yayasan)])}
async function pairOK(c:Caller,sp:unknown,ya:unknown){if(c.role==='SUPER_ADMIN')return true;if(c.role!=='ADMIN')return false;const x=s(sp),y=s(ya);return(await pairs(c)).some(([a,b])=>a===x&&b===y)}
async function access(c:Caller,r:any){if(c.role==='SUPER_ADMIN')return true;if(c.role==='ADMIN')return pairOK(c,r.SPPG,r.YAYASAN);return lo(r.User)===c.email}
async function tx(c:Caller,id:string){const q=await sb.from(T.X).select('*').eq('ID',id).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error('Transaksi tidak ditemukan.');if(!(await access(c,q.data)))throw new Error('Akses transaksi ditolak.');return q.data}
async function upload(kind:keyof typeof B,b64:string,mime:string,name:string,prefix:string){const rules:any={foto:/^image\/(jpeg|jpg|png|webp|heic|heif)$/i,file:/^(application\/pdf|image\/(jpeg|jpg|png|webp|heic|heif))$/i,ttdUser:/^image\/(png|jpeg|jpg|webp)$/i,nota:/^(application\/pdf|image\/(jpeg|jpg|png|webp|heic|heif))$/i,ttdVerif:/^image\/(png|jpeg|jpg|webp)$/i,payment:/^(application\/pdf|image\/(jpeg|jpg|png|webp|heic|heif))$/i};if(!rules[kind].test(s(mime)))throw new Error('Tipe MIME file tidak diizinkan.');if(!b64||!name)throw new Error('Data file tidak lengkap.');const path=`${prefix}_${Date.now()}_${crypto.randomUUID()}_${s(name).replace(/[^a-zA-Z0-9._-]/g,'_')}`;const q=await sb.storage.from(B[kind]).upload(path,bytes(b64),{contentType:mime,upsert:false});if(q.error)throw new Error(`Upload gagal: ${q.error.message}`);return path}
async function signDoc(d?:Doc){if(!d||!valid(d.storage_path))return null;const q=await sb.storage.from(d.storage_bucket).createSignedUrl(s(d.storage_path),3600);if(q.error||!q.data?.signedUrl)return null;return{path:s(d.storage_path),bucket:d.storage_bucket,name:s(d.original_file_name)||s(d.storage_path).split('/').pop(),signedUrl:q.data.signedUrl,signedThumbnailUrl:q.data.signedUrl,mimeType:d.mime_type||null}}
async function sign(kind:keyof typeof B,path:unknown,mime?:string){return signDoc(valid(path)?{transaksi_id:'',document_type:'',storage_bucket:B[kind],storage_path:s(path),mime_type:mime}:undefined)}
async function audit(id:string,action:string,c:Caller,detail:any){try{await sb.from(T.L).insert({TIMESTAMP:new Date().toISOString(),USER_EMAIL:c.email,USER_NAME:c.nama,ROLE:c.role,SPPG:c.sppg,ACTION_TYPE:action,TABLE_NAME:T.X,RECORD_ID:id,FIELD_CHANGED:'TRANSACTION_SECURITY',OLD_VALUE:'',NEW_VALUE:JSON.stringify(detail).slice(0,500),DESCRIPTION:`${action} ${T.X}`,IP_USER:'',STATUS:'SUCCESS'})}catch(e){console.error('audit',e)}}
function txPageSpec(v:any){const requested=Number(v?.page)>0||Number(v?.pageSize)>0;if(!requested)return null;const page=Math.max(1,Math.floor(Number(v?.page)||1));const pageSize=Math.min(100,Math.max(1,Math.floor(Number(v?.pageSize)||25)));return{page,pageSize,from:(page-1)*pageSize,to:page*pageSize-1}}
async function list(filters:any,c:Caller){let q=sb.from(T.X).select('*').order('Tanggal',{ascending:false});if(filters?.sppg&&filters.sppg!=='ALL')q=q.eq('SPPG',filters.sppg);if(filters?.yayasan&&filters.yayasan!=='ALL')q=q.eq('YAYASAN',filters.yayasan);if(filters?.kategori&&filters.kategori!=='ALL')q=q.eq('Kategori',filters.kategori);if(filters?.dateStart)q=q.gte('Tanggal',date(filters.dateStart));if(filters?.dateEnd)q=q.lte('Tanggal',date(filters.dateEnd));const r=await q;if(r.error)throw r.error;const rows=[];for(const row of r.data||[])if(await access(c,row))rows.push(row);const dm=await docsFor(rows.map(x=>s(x.ID)));const out=rows.map(row=>map(row,dm.get(s(row.ID))||legacyDocs(row)));const pg=txPageSpec(filters);if(!pg)return out;const total=out.length;return{data:out.slice(pg.from,pg.to+1),page:pg.page,pageSize:pg.pageSize,total,hasMore:pg.to+1<total}}
async function detail(id:string,c:Caller){const r=await tx(c,id);const d=(await docsFor([id])).get(id)||legacyDocs(r);const p=await sb.from(T.P).select('*').eq('transaksi_id',id).order('payment_sequence',{ascending:true});if(p.error)throw p.error;const proofs=[];for(const x of p.data||[])proofs.push({...x,nominal:Number(x.nominal)||0,file:await sign('payment',x.storage_path,x.mime_type),verifierSignature:await sign('ttdVerif',x.verifier_signature_path,'image/png')});return{...map(r,d),fileBuktiFoto:await signDoc(d.get(DT.foto)),fileBuktiFile:await signDoc(d.get(DT.file)),fileBuktiApproval:await signDoc(d.get(DT.approval)),fileNota:await signDoc(d.get(DT.nota)),fileTtdUser:await signDoc(d.get(DT.ttdUser)),fileTtdVerif:await signDoc(d.get(DT.ttdVerif)),paymentProofs:proofs}}
function ownedUpload(c:Caller,kind:string,path:unknown){return valid(path)&&s(path).startsWith(`${kind}_${c.id}_`)}
function txFileItems(r:any){return[{kind:'foto',bucket:B.foto,path:s(r['UPLOUD FOTO'])},{kind:'file',bucket:B.file,path:s(r['UPLOUD FILE'])},{kind:'ttdUser',bucket:B.ttdUser,path:s(r['TTD USER'])},{kind:'nota',bucket:B.nota,path:s(r['NOTA PEMBELIAN'])}]}
async function systemNotify(payload:any){try{const base=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!base||!service)return;const r=await fetch(base+'/functions/v1/notification-dispatch-action',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+service},body:JSON.stringify({function:'dispatchSystemNotification',parameters:[payload]})});if(!r.ok)console.error('notification dispatch failed',r.status,await r.text())}catch(e){console.error('notification dispatch error',e)}}
async function add(d:any,c:Caller){const sp=(c.role==='ADMIN'||c.role==='SUPER_ADMIN')?s(d.sppg||c.sppg):c.sppg;const ya=(c.role==='ADMIN'||c.role==='SUPER_ADMIN')?s(d.yayasan||c.yayasan):c.yayasan;if(!sp||!ya)throw new Error('SPPG dan YAYASAN wajib tersedia.');if(c.role==='ADMIN'&&!(await pairOK(c,sp,ya)))throw new Error('Pasangan SPPG + YAYASAN tidak di-assign.');if(!(Number(d.nominal)>0))throw new Error('Nominal transaksi harus lebih dari 0.');const id=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();const row:any={ID:id,'Kode Pemasukan':`TRX - ${crypto.randomUUID().slice(0,8)}`,Tanggal:date(d.tanggal),Kategori:s(d.kategori),'Jenis Kategori':s(d.jenisKategori),SPPG:sp,YAYASAN:ya,Nominal:Number(d.nominal),'UPLOUD FOTO':s(d.uploadFoto),'UPLOUD FILE':s(d.uploadFile),Catatan:s(d.catatan),Timestamp:new Date().toISOString(),User:c.email,'Nama Item/ Bahan Baku':s(d.namaItem||d.item),'Metode Transaksi':status(d.metodeTransaksi),'TTD VERIFIKATOR':'','TTD USER':s(d.ttdUser),'NOTA PEMBELIAN':s(d.notaPembelian),'APPROVED BY':'','WAKTU APPROVE':null,'LINK FOTO/ FILE  BUKTI TRANSAKSI':'','LINK  TTD USER':'','LINK FOTO NOTA':'',Catatan_1:'','Catatan Approval':'',Deskripsi:''};const docs=legacyDocs(row);const miss=missingDocs(docs);if(miss.length)throw new Error(`Upload wajib belum lengkap atau gagal: ${miss.join(', ')}.`);row['STATUS DOKUMEN']=docStatus(docs);const uploaded=txFileItems(row).filter(x=>ownedUpload(c,x.kind,x.path)).map(x=>({bucket:x.bucket,path:x.path}));try{const q=await sb.from(T.X).insert(row).select().single();if(q.error)throw q.error;await audit(id,'ADD',c,{sp,ya,compatibilityWrite:true});await systemNotify({mode:'pair',sppg:sp,yayasan:ya,title:'Transaksi baru',body:`Transaksi ${id} sebesar Rp ${Number(d.nominal).toLocaleString('id-ID')} telah dibuat.`,url:'/?page=transaksi'});const nd=(await docsFor([id])).get(id)||docs;return{success:true,message:'Transaksi berhasil ditambahkan.',id,data:map(q.data,nd)}}catch(e){await removeFiles(uploaded).catch(err=>console.error('cleanup add orphan',err));throw e}}
async function edit(id:string,f:any,c:Caller){const old=await tx(c,id);const m:any={'Tanggal':'Tanggal','Kategori':'Kategori','Jenis Kategori':'Jenis Kategori','SPPG':'SPPG','YAYASAN':'YAYASAN','Nama Item/Bahan Baku':'Nama Item/ Bahan Baku','Nominal':'Nominal','Catatan':'Catatan','Metode Transaksi':'Metode Transaksi','Upload Foto':'UPLOUD FOTO','Upload File':'UPLOUD FILE','Nota Pembelian':'NOTA PEMBELIAN','TTD User':'TTD USER'};const patch:any={};for(const[k,v]of Object.entries(f||{}))if(m[k])patch[m[k]]=m[k]==='Tanggal'?date(v):v;const sp=s(patch.SPPG??old.SPPG),ya=s(patch.YAYASAN??old.YAYASAN);if(c.role==='ADMIN'&&!(await pairOK(c,sp,ya)))throw new Error('Pasangan SPPG + YAYASAN tujuan tidak di-assign.');if(!['ADMIN','SUPER_ADMIN'].includes(c.role)){delete patch.SPPG;delete patch.YAYASAN;delete patch['Metode Transaksi']}const proofState=await sb.from(T.P).select('nominal,status').eq('transaksi_id',id);if(proofState.error)throw proofState.error;let submitted=0,verified=0,pendingCount=0;for(const proof of proofState.data||[]){const amount=Number(proof.nominal)||0,ps=status(proof.status);if(ps!=='DITOLAK')submitted+=amount;if(ps==='TERVERIFIKASI')verified+=amount;if(ps==='MENUNGGU_VERIFIKASI')pendingCount++}const targetNominal=Object.prototype.hasOwnProperty.call(patch,'Nominal')?Number(patch.Nominal):Number(old.Nominal);if(!(targetNominal>0))throw new Error('Nominal transaksi harus lebih dari 0.');if(targetNominal<submitted)throw new Error('Nominal transaksi tidak boleh lebih kecil dari pembayaran yang sudah diajukan.');if((proofState.data||[]).length){if(verified>=targetNominal)patch['Metode Transaksi']='SUDAH_DIBAYAR';else if(submitted>=targetNominal&&pendingCount>0)patch['Metode Transaksi']='MENUNGGU_VERIFIKASI';else patch['Metode Transaksi']='BELUM_LUNAS'}const merged={...old,...patch},md=legacyDocs(merged),miss=missingDocs(md);if(miss.length)throw new Error(`Upload wajib belum lengkap atau gagal: ${miss.join(', ')}.`);patch['STATUS DOKUMEN']=docStatus(md);const before=txFileItems(old),after=txFileItems(merged);const fresh=after.filter((x,i)=>x.path!==before[i].path&&ownedUpload(c,x.kind,x.path)).map(x=>({bucket:x.bucket,path:x.path}));const obsolete=before.filter((x,i)=>valid(x.path)&&x.path!==after[i].path).map(x=>({bucket:x.bucket,path:x.path}));try{const q=await sb.from(T.X).update(patch).eq('ID',id).select().single();if(q.error)throw q.error;await removeFiles(obsolete).catch(err=>console.error('cleanup replaced files',err));await audit(id,'EDIT',c,{fields:Object.keys(patch),compatibilityWrite:true});const nd=(await docsFor([id])).get(id)||legacyDocs(q.data);return{success:true,message:'Transaksi berhasil diubah.',data:map(q.data,nd)}}catch(e){await removeFiles(fresh).catch(err=>console.error('cleanup edit orphan',err));throw e}}
async function note(p:any[],c:Caller){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Akses ditolak.');const a=p[0],id=typeof a==='object'?s(a.txId||a.id):s(a),n=typeof a==='object'?s(a.note||a.catatanApproval||a.catatan):s(p[1]);await tx(c,id);const q=await sb.from(T.X).update({'Catatan Approval':n,Catatan_1:n}).eq('ID',id);if(q.error)throw q.error;return{success:true,message:'Catatan berhasil disimpan.'}}
async function uploadFile(p:any[],c:Caller){const kind=s(p[3]) as keyof typeof B;if(!['foto','file','ttdUser','nota'].includes(kind))throw new Error('Tipe file transaksi tidak diizinkan.');const path=await upload(kind,p[0],p[1],p[2],`${kind}_${c.id}`);return{success:true,fileName:path,bucket:B[kind],viewUrl:(await sign(kind,path,p[1]))?.signedUrl||''}}
async function removeFiles(items:{bucket:string,path:unknown}[]){const grouped=new Map<string,string[]>();for(const x of items){if(!valid(x.path)||!x.bucket)continue;const a=grouped.get(x.bucket)||[];if(!a.includes(s(x.path)))a.push(s(x.path));grouped.set(x.bucket,a)}for(const[bucket,paths]of grouped){if(!paths.length)continue;const q=await sb.storage.from(bucket).remove(paths);if(q.error)throw new Error(`Gagal membersihkan Storage ${bucket}: ${q.error.message}`)}}
async function del(id:string,c:Caller){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Hanya ADMIN yang dapat menghapus transaksi.');const r=await tx(c,id);const dq=await sb.from(T.D).select('storage_bucket,storage_path').eq('transaksi_id',id);if(dq.error)throw dq.error;const pq=await sb.from(T.P).select('storage_bucket,storage_path,verifier_signature_path').eq('transaksi_id',id);if(pq.error)throw pq.error;const files:{bucket:string,path:unknown}[]=(dq.data||[]).map((x:any)=>({bucket:s(x.storage_bucket),path:x.storage_path}));for(const p of pq.data||[])files.push({bucket:s(p.storage_bucket)||B.payment,path:p.storage_path},{bucket:B.ttdVerif,path:p.verifier_signature_path});await removeFiles(files);const q=await sb.from(T.X).delete().eq('ID',id);if(q.error)throw q.error;await audit(id,'DELETE',c,{storageFilesDeleted:files.filter(x=>valid(x.path)).length,documentSource:T.D});return{success:true,message:'Transaksi dan file Storage terkait berhasil dihapus.'}}
const H:any={getTransactions:(p:any[],c:Caller)=>list(p[0]||{},c),getTransactionDetail:(p:any[],c:Caller)=>detail(s(p[0]),c),addTransaction:(p:any[],c:Caller)=>add(p[0]||{},c),editTransaction:(p:any[],c:Caller)=>edit(s(p[0]),p[1]||{},c),sendCatatanApproval:note,uploadTxFile:uploadFile,deleteTransaction:(p:any[],c:Caller)=>del(s(p[0]),c)};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method==='GET')return j({status:'ok',service:'transaction-action',version:4,documentReadSource:T.D,writeMode:'legacy-compatible'});if(req.method!=='POST')return j({error:'Method tidak didukung.'},405);try{const c=await caller(req),body=await req.json(),fn=H[body?.function];if(!fn)return j({error:`Fungsi tidak diizinkan: ${body?.function||''}`},404);const result=await fn(Array.isArray(body.parameters)?body.parameters:[],c);return j({result})}catch(e){const message=e instanceof Error?e.message:String(e);const denied=/akses|token|hanya admin|di-assign/i.test(message);console.error(message);return j({error:message,result:{success:false,message}},denied?403:400)}});
