import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';
export const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
export const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
export const B={supplierFoto:'foto-supplier',supplierTtd:'ttd-supplier-inv',supplierMou:'file-mou',survei:'foto-bb',serah:'foto-datang',ttdPenerima:'ttd-penerima',ttdSupplier:'ttd-supplier-inv'} as const;
export type Caller={id:string,email:string,username:string,role:string,jabatan:string,sppg:string,yayasan:string,nama:string};
export const s=(v:any)=>String(v??'').trim();export const low=(v:any)=>s(v).toLowerCase();
export const out=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...C,'Content-Type':'application/json'}});
export async function caller(req:Request):Promise<Caller>{const h=req.headers.get('Authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)throw new Error('Token tidak ditemukan.');const a=await sb.auth.getUser(token);if(a.error||!a.data.user)throw new Error('Token tidak valid atau kedaluwarsa.');const q=await sb.from('USERS').select('ID,EMAIL,USERNAME,ROLE,JABATAN,SPPG,"NAMA YAYASAN","NAMA LENGKAP"').eq('ID',a.data.user.id).maybeSingle();if(q.error||!q.data)throw new Error('Profil user tidak ditemukan.');return{id:q.data.ID,email:low(a.data.user.email||q.data.EMAIL),username:s(q.data.USERNAME),role:s(q.data.ROLE).toUpperCase(),jabatan:s(q.data.JABATAN),sppg:s(q.data.SPPG),yayasan:s(q.data['NAMA YAYASAN']),nama:s(q.data['NAMA LENGKAP'])}}
export function requireAdmin(c:Caller){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Hanya ADMIN yang dapat melakukan perubahan master data.');}
export async function exactPairs(c:Caller){if(c.role==='SUPER_ADMIN')return null;const q=await sb.from('ADMIN_ASSIGNMENT').select('sppg,yayasan').eq('admin_email',c.email);if(q.error)throw q.error;return(q.data||[]).map((r:any)=>[s(r.sppg),s(r.yayasan)] as const)}
export async function canAccessOwner(c:Caller,owner:any,yayasan:any){if(c.role==='SUPER_ADMIN')return true;if(c.role!=='ADMIN')return low(owner)===c.email||low(owner)===low(c.username);const u=await sb.from('USERS').select('SPPG,"NAMA YAYASAN"').or(`EMAIL.eq.${low(owner)},USERNAME.eq.${s(owner)}`).limit(1).maybeSingle();if(u.error||!u.data)return false;const pairs=await exactPairs(c);return !!pairs?.some(([sp,ya])=>sp===s(u.data.SPPG)&&ya===s(yayasan||u.data['NAMA YAYASAN']))}
export async function audit(c:Caller,id:string,action:string,table:string,detail:any){try{await sb.from('AUDIT LOG').insert({TIMESTAMP:new Date().toISOString(),USER_EMAIL:c.email,USER_NAME:c.nama,ROLE:c.role,SPPG:c.sppg,ACTION_TYPE:action,TABLE_NAME:table,RECORD_ID:id,FIELD_CHANGED:'HARDENED_MASTER',OLD_VALUE:'',NEW_VALUE:JSON.stringify(detail).slice(0,500),DESCRIPTION:`${action} ${table}`,IP_USER:'',STATUS:'SUCCESS'})}catch(e){console.error(e)}}
export function rid(){return crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}
function bytes(v:string){const raw=v.includes(',')?v.split(',').pop()!:v;const bin=atob(raw);const x=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)x[i]=bin.charCodeAt(i);return x}
export async function upload(bucket:keyof typeof B,b64:string,mime:string,name:string,prefix:string){const rules:any={supplierFoto:/^image\/(jpeg|jpg|png|webp)$/i,supplierTtd:/^image\/(jpeg|jpg|png|webp)$/i,supplierMou:/^(application\/pdf|image\/(jpeg|jpg|png|webp))$/i,survei:/^image\/(jpeg|jpg|png|webp)$/i,serah:/^image\/(jpeg|jpg|png|webp)$/i,ttdPenerima:/^image\/(jpeg|jpg|png|webp)$/i,ttdSupplier:/^image\/(jpeg|jpg|png|webp)$/i};if(!rules[bucket].test(mime))throw new Error('Tipe MIME file tidak diizinkan.');const data=bytes(b64);if(data.byteLength>10*1024*1024)throw new Error('Ukuran file maksimal 10 MB.');const path=`${prefix}_${Date.now()}_${crypto.randomUUID()}_${s(name).replace(/[^a-zA-Z0-9._-]/g,'_')}`;const q=await sb.storage.from(B[bucket]).upload(path,data,{contentType:mime,upsert:false});if(q.error)throw new Error(q.error.message);const signed=await sb.storage.from(B[bucket]).createSignedUrl(path,3600);return{success:true,fileName:path,bucket:B[bucket],viewUrl:signed.data?.signedUrl||''}}
export async function removeFiles(items:{bucket:string,path:any}[]){for(const x of items){if(!s(x.path))continue;const q=await sb.storage.from(x.bucket).remove([s(x.path)]);if(q.error)throw new Error(`Gagal menghapus file ${x.bucket}: ${q.error.message}`)}}