import {CORS,json,text,sb,getCaller,applyRoleFilter,handlerError} from '../_shared/chattrx.ts';
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'Method tidak didukung.'},405);try{
  const c=await getCaller(req),body=await req.json(),p=Array.isArray(body.parameters)?body.parameters[0]||{}:body;let q:any=sb.from('CHATTRX_DRAFT').select('*').eq('draft_id',text(p.draftId)).maybeSingle();const r=await applyRoleFilter(q,c);if(r.error)throw r.error;const d=r.data;if(!d)throw new Error('Draft tidak ditemukan atau akses ditolak.');
  if(d.current_state!=='ringkasan'||d.verifikasi_nota?.valid!==true||(d.status_pembayaran==='sudah_dibayar'&&d.verifikasi_bukti_bayar?.valid!==true))throw new Error('Draft belum lengkap atau bukti belum terverifikasi.');
  const signature=String(p.ttdBase64||'').replace(/^data:image\/png;base64,/, '');if(!signature)throw new Error('TTD konfirmasi wajib dibubuhkan sebelum menyimpan.');
  const sigPath=`${c.id}/${d.draft_id}/ttd-${crypto.randomUUID()}.png`,sig=Uint8Array.from(atob(signature),x=>x.charCodeAt(0));const su=await sb.storage.from('chattrx-evidence').upload(sigPath,sig,{contentType:'image/png',upsert:false});if(su.error)throw su.error;
  const row={draft_id:d.draft_id,user_id:d.user_id,sppg:d.sppg,yayasan:d.yayasan,jenis_transaksi:d.jenis_transaksi,kategori:d.kategori,nama_item:d.nama_item,keterangan:d.keterangan,nominal:Number(d.nominal),status_pembayaran:d.status_pembayaran,foto_nota_url:d.foto_nota_url,foto_bukti_bayar_url:d.foto_bukti_bayar_url||null,ttd_konfirmasi_url:sigPath,verifikasi_nota:d.verifikasi_nota,verifikasi_bukti_bayar:d.verifikasi_bukti_bayar||null,chat_history:d.chat_history||[]};
  const saved=await sb.from('CHATTRX_TRANSAKSI').upsert(row,{onConflict:'draft_id'}).select('transaksi_id').single();if(saved.error)throw saved.error;
  const u=await sb.from('CHATTRX_DRAFT').update({status:'confirmed',updated_at:new Date().toISOString()}).eq('draft_id',d.draft_id);if(u.error)throw u.error;return json({result:{success:true,message:'Transaksi ChatTrx berhasil disimpan.',transactionId:saved.data.transaksi_id}})
}catch(e){return handlerError(e)}});
