import {CORS,json,text,sb,getCaller,applyRoleFilter,handlerError} from '../_shared/chattrx.ts';
async function copyEvidence(path:string,bucket:string,target:string){const d=await sb.storage.from('chattrx-evidence').download(path);if(d.error)throw d.error;const u=await sb.storage.from(bucket).upload(target,await d.data.arrayBuffer(),{contentType:d.data.type||'image/jpeg',upsert:false});if(u.error)throw u.error;return target}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'Method tidak didukung.'},405);try{
  const c=await getCaller(req),body=await req.json(),p=Array.isArray(body.parameters)?body.parameters[0]||{}:body;let q:any=sb.from('CHATTRX_DRAFT').select('*').eq('draft_id',text(p.draftId)).maybeSingle();const r=await applyRoleFilter(q,c);if(r.error)throw r.error;const d=r.data;if(!d)throw new Error('Draft tidak ditemukan atau akses ditolak.');
  if(d.current_state!=='ringkasan'||d.verifikasi_nota?.valid!==true||(d.status_pembayaran==='sudah_dibayar'&&d.verifikasi_bukti_bayar?.valid!==true))throw new Error('Draft belum lengkap atau bukti belum terverifikasi.');
  const signature=String(p.ttdBase64||'').replace(/^data:image\/png;base64,/, '');if(!signature)throw new Error('TTD konfirmasi wajib dibubuhkan sebelum menyimpan.');
  const nonce=crypto.randomUUID(),nota=await copyEvidence(d.foto_nota_url,'nota-pembelian',`${c.id}/chattrx-${nonce}-nota.jpg`);let proof='';if(d.foto_bukti_bayar_url)proof=await copyEvidence(d.foto_bukti_bayar_url,'transaksi-images',`${c.id}/chattrx-${nonce}-bayar.jpg`);
  const sigPath=`${c.id}/chattrx-${nonce}-ttd.png`,sig=Uint8Array.from(atob(signature),x=>x.charCodeAt(0));const su=await sb.storage.from('paraf-user').upload(sigPath,sig,{contentType:'image/png',upsert:false});if(su.error)throw su.error;
  const payload={tanggal:new Date().toISOString().slice(0,10),kategori:d.jenis_transaksi==='pemasukan'?'PEMASUKAN':'PENGELUARAN',jenisKategori:d.kategori,namaItem:d.nama_item,catatan:d.keterangan,nominal:Number(d.nominal),metodeTransaksi:d.status_pembayaran==='sudah_dibayar'?'SUDAH_DIBAYAR':'BELUM_BAYAR',sppg:d.sppg,yayasan:d.yayasan,notaPembelian:nota,ttdUser:sigPath,uploadFoto:proof};
  const h=req.headers.get('Authorization')||'',call=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/transaction-action`,{method:'POST',headers:{Authorization:h,apikey:Deno.env.get('SUPABASE_ANON_KEY')||'', 'Content-Type':'application/json'},body:JSON.stringify({function:'addTransaction',parameters:[payload]})});const raw=await call.json();const result=raw?.result;if(!call.ok||!result?.success)throw new Error(result?.message||raw?.error||'Transaksi gagal disimpan melalui transaction-action.');
  const u=await sb.from('CHATTRX_DRAFT').update({status:'confirmed',updated_at:new Date().toISOString()}).eq('draft_id',d.draft_id);if(u.error)throw u.error;return json({result:{success:true,message:'Transaksi berhasil disimpan.',transactionId:result.id}})
}catch(e){return handlerError(e)}});
