import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';

const sb = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth:{persistSession:false,autoRefreshToken:false} });
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const j=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}});
const s=(v:unknown)=>String(v??'').trim(); const lo=(v:unknown)=>s(v).toLowerCase();
type Caller={id:string,email:string,username:string,role:string,sppg:string,yayasan:string,nama:string};

async function caller(req:Request):Promise<Caller>{
  const h=req.headers.get('Authorization')||''; const token=h.startsWith('Bearer ')?h.slice(7):'';
  if(!token) throw new Error('Token tidak ditemukan.');
  const {data,error}=await sb.auth.getUser(token); if(error||!data.user) throw new Error('Token tidak valid atau kedaluwarsa.');
  const q=await sb.from('USERS').select('ID,EMAIL,USERNAME,ROLE,SPPG,"NAMA YAYASAN","NAMA LENGKAP"').eq('ID',data.user.id).maybeSingle();
  if(q.error||!q.data) throw new Error('Profil user tidak ditemukan.');
  return{id:data.user.id,email:lo(data.user.email||q.data.EMAIL),username:lo(q.data.USERNAME),role:s(q.data.ROLE).toUpperCase(),sppg:s(q.data.SPPG),yayasan:s(q.data['NAMA YAYASAN']),nama:s(q.data['NAMA LENGKAP'])};
}
async function assignments(c:Caller){if(c.role!=='ADMIN')return[];const q=await sb.from('ADMIN_ASSIGNMENT').select('sppg,yayasan').eq('admin_email',c.email);if(q.error)throw q.error;return(q.data||[]).map((r:any)=>[s(r.sppg),s(r.yayasan)] as [string,string]);}
async function pairOK(c:Caller,sp:unknown,ya:unknown){if(c.role==='SUPER_ADMIN')return true;if(c.role!=='ADMIN')return false;const x=s(sp),y=s(ya);return(await assignments(c)).some(([a,b])=>a===x&&b===y);}
async function profileByOwner(owner:unknown){const x=lo(owner);if(!x)return null;const q=await sb.from('USERS').select('ID,EMAIL,USERNAME,ROLE,SPPG,"NAMA YAYASAN","NAMA LENGKAP"').or(`EMAIL.eq.${x},USERNAME.eq.${x}`).limit(1).maybeSingle();if(q.error)throw q.error;return q.data;}
async function ownerOK(c:Caller,owner:unknown){if(c.role==='SUPER_ADMIN')return true;const x=lo(owner);if(c.role==='USER')return x===c.email||x===c.username;if(c.role!=='ADMIN')return false;const p=await profileByOwner(owner);return !!p&&await pairOK(c,p.SPPG,p['NAMA YAYASAN']);}
async function requireRecord(c:Caller,table:string,id:string,ownerCol='USER'){const q=await sb.from(table).select('*').eq('ID',id).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error('Data tidak ditemukan.');if(!(await ownerOK(c,q.data[ownerCol])))throw new Error('Akses record ditolak.');return q.data;}
async function audit(c:Caller,table:string,id:string,action:string,detail:any){try{await sb.from('AUDIT LOG').insert({TIMESTAMP:new Date().toISOString(),USER_EMAIL:c.email,USER_NAME:c.nama,ROLE:c.role,SPPG:c.sppg,ACTION_TYPE:action,TABLE_NAME:table,RECORD_ID:id,FIELD_CHANGED:'HARDENED_AUTH',OLD_VALUE:'',NEW_VALUE:JSON.stringify(detail).slice(0,500),DESCRIPTION:`${action} ${table}`,IP_USER:'',STATUS:'SUCCESS'})}catch(e){console.error('audit',e)}}
function pageSpec(v:any){const requested=Number(v?.page)>0||Number(v?.pageSize)>0;if(!requested)return null;const page=Math.max(1,Math.floor(Number(v?.page)||1));const pageSize=Math.min(100,Math.max(1,Math.floor(Number(v?.pageSize)||25)));return{page,pageSize,from:(page-1)*pageSize,to:page*pageSize-1}}
function paged(data:any[],v:any){const x=pageSpec(v);if(!x)return null;const total=data.length;return{data:data.slice(x.from,x.to+1),page:x.page,pageSize:x.pageSize,total,hasMore:x.to+1<total}}

async function getAllUsers(c:Caller,opt:any={}){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Akses ditolak.');const q=await sb.from('USERS').select('ID,"NAMA LENGKAP",EMAIL,JABATAN,SPPG,ROLE,"FOTO PROFIL",TIMESTAMP,USERNAME,"NAMA YAYASAN"').order('TIMESTAMP',{ascending:false});if(q.error)throw q.error;const out=[];for(const r of q.data||[]){if(c.role==='SUPER_ADMIN'||await pairOK(c,r.SPPG,r['NAMA YAYASAN']))out.push({id:r.ID,namaLengkap:r['NAMA LENGKAP'],email:r.EMAIL,jabatan:r.JABATAN,sppg:r.SPPG,role:r.ROLE,fotoProfil:r['FOTO PROFIL'],timestamp:r.TIMESTAMP,username:r.USERNAME,namaYayasan:r['NAMA YAYASAN']||''});}const pg=paged(out,opt);return pg?{success:true,...pg}:{success:true,data:out};}
async function deleteUser(username:string,c:Caller){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Akses ditolak.');const q=await sb.from('USERS').select('*').eq('USERNAME',lo(username)).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error('User tidak ditemukan.');if(q.data.ID===c.id)throw new Error('Tidak bisa menghapus akun sendiri.');if(q.data.ROLE==='SUPER_ADMIN')throw new Error('Akun SUPER_ADMIN tidak dapat dihapus dari endpoint ini.');if(c.role==='ADMIN'){if(q.data.ROLE!=='USER')throw new Error('ADMIN hanya dapat menghapus USER.');if(!(await pairOK(c,q.data.SPPG,q.data['NAMA YAYASAN'])))throw new Error('Target di luar assignment ADMIN.');}
  const a=await sb.auth.admin.deleteUser(q.data.ID);if(a.error)throw a.error;const d=await sb.from('USERS').delete().eq('ID',q.data.ID);if(d.error)throw d.error;await audit(c,'USERS',q.data.ID,'DELETE',{username});return{success:true,message:'User berhasil dihapus.'};}

async function listOwned(table:string,c:Caller,orderCol='TIMESTAMP'){const q=await sb.from(table).select('*').order(orderCol,{ascending:false});if(q.error)throw q.error;const out=[];for(const r of q.data||[])if(await ownerOK(c,r.USER))out.push(r);return out;}
function ownedResult(data:any[],opt:any={}){const pg=paged(data,opt);return pg?{success:true,...pg}:{success:true,data}}
async function getPending(c:Caller,opt:any={}){return ownedResult(await listOwned('Pending Payment',c,'Timestamp'),opt);}
async function updatePending(id:string,data:any,c:Caller){await requireRecord(c,'Pending Payment',id,'User');if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Hanya ADMIN yang dapat memperbarui.');const p:any={};if(data.status!==undefined)p.Status=data.status;if(data.tanggalLunas!==undefined)p['Tanggal Lunas']=data.tanggalLunas||null;if(data.buktiPembayaran!==undefined)p['Bukti Pembayaran']=data.buktiPembayaran;if(data.catatan!==undefined)p.Catatan=data.catatan;const q=await sb.from('Pending Payment').update(p).eq('ID',id);if(q.error)throw q.error;await audit(c,'Pending Payment',id,'EDIT',Object.keys(p));return{success:true,message:'Pending Payment diperbarui.'};}
async function delRecord(table:string,id:string,c:Caller,ownerCol='USER'){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Hanya ADMIN yang dapat menghapus.');await requireRecord(c,table,id,ownerCol);const q=await sb.from(table).delete().eq('ID',id);if(q.error)throw q.error;await audit(c,table,id,'DELETE',{});return{success:true,message:'Data berhasil dihapus.'};}
async function updateRecord(table:string,id:string,fields:any,c:Caller,allowed:string[],ownerCol='USER'){if(!['ADMIN','SUPER_ADMIN'].includes(c.role))throw new Error('Hanya ADMIN yang dapat mengubah.');await requireRecord(c,table,id,ownerCol);const p:any={};for(const k of allowed)if(Object.prototype.hasOwnProperty.call(fields||{},k))p[k]=fields[k];if(!Object.keys(p).length)throw new Error('Tidak ada field yang dapat diperbarui.');const q=await sb.from(table).update(p).eq('ID',id);if(q.error)throw q.error;await audit(c,table,id,'EDIT',Object.keys(p));return{success:true,message:'Data berhasil diperbarui.'};}
async function getMenu(c:Caller,filters:any){const menus=await listOwned('MENU_HARIAN',c,'TIMESTAMP');let out=menus;if(filters?.dateStart)out=out.filter((r:any)=>s(r.TANGGAL)>=s(filters.dateStart));if(filters?.dateEnd)out=out.filter((r:any)=>s(r.TANGGAL)<=s(filters.dateEnd));const total=out.length,ps=pageSpec(filters),selected=ps?out.slice(ps.from,ps.to+1):out;const ids=selected.map((r:any)=>r.ID);let details:any[]=[];if(ids.length){const q=await sb.from('DETAIL_MENU_HARIAN').select('*').in('MENU_ID',ids);if(q.error)throw q.error;details=q.data||[];}const data=selected.map((r:any)=>({id:r.ID,tanggal:r.TANGGAL,jumlahKpm:r['JUMLAH KPM']||0,menu:r.MENU||'',user:r.USER||'',detail:details.filter((d:any)=>d.MENU_ID===r.ID).map((d:any)=>({namaItem:d['Nama Item']||'',jumlah:d.Jumlah||0,satuan:d.Satuan||'',hargaSatuan:d['Harga Satuan']||0,totalHarga:d['Total Harga']||0}))}));return ps?{success:true,data,page:ps.page,pageSize:ps.pageSize,total,hasMore:ps.to+1<total}:{success:true,data};}

const SURVEI_FIELDS=['KODE BAHAN BAKU','KATEGORI BAHAN BAKU','NAMA BAHAN BAKU','HARGA RAB','HARGA PASAR','ALAMAT SURVEI','LOKASI SURVEI','FOTO BAHAN BAKU','LINK FOTO BAHAN BAKU'];
const SERAH_FIELDS=['KODE BAHAN BAKU','KATEGORI BAHAN BAKU','NAMA BAHAN BAKU','FOTO BARANG DATANG','LINK FOTO BARANG DATANG','FOTO SURAT JALAN','LINK FOTO SURAT JALAN','PENERIMA','TTD PENERIMA','LINK TTD PENERIMA','SUPPLIER','TTD SUPPLIER','LINK TTD SUPPLIER','KONDISI BAHAN BAKU','CATATAN','LOKASI'];
const MENU_FIELDS=['TANGGAL','JUMLAH KPM','MENU'];
const H:any={
 getAllUsers:(p:any[],c:Caller)=>getAllUsers(c,p[0]||{}),deleteUser:(p:any[],c:Caller)=>deleteUser(s(p[0]),c),
 getPendingPayments:(p:any[],c:Caller)=>getPending(c,p[0]||{}),updatePendingPayment:(p:any[],c:Caller)=>updatePending(s(p[0]),p[1]||{},c),deletePendingPayment:(p:any[],c:Caller)=>delRecord('Pending Payment',s(p[0]),c,'User'),
 getSurveiBahanBaku:async(p:any[],c:Caller)=>ownedResult(await listOwned('SURVEI_BB',c),p[0]||{}),updateSurvei:(p:any[],c:Caller)=>updateRecord('SURVEI_BB',s(p[0]),p[1]||{},c,SURVEI_FIELDS),deleteSurvei:(p:any[],c:Caller)=>delRecord('SURVEI_BB',s(p[0]),c),
 getSerahTerima:async(p:any[],c:Caller)=>ownedResult(await listOwned('SERAH_TERIMA',c),p[0]||{}),updateSerahTerima:(p:any[],c:Caller)=>updateRecord('SERAH_TERIMA',s(p[0]),p[1]||{},c,SERAH_FIELDS),deleteSerahTerima:(p:any[],c:Caller)=>delRecord('SERAH_TERIMA',s(p[0]),c),
 getMenuHarian:(p:any[],c:Caller)=>getMenu(c,p[0]||{}),updateMenuMBG:(p:any[],c:Caller)=>updateRecord('MENU_HARIAN',s(p[0]),p[1]||{},c,MENU_FIELDS),deleteMenuMBG:(p:any[],c:Caller)=>delRecord('MENU_HARIAN',s(p[0]),c)
};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method==='GET')return j({status:'ok',service:'operations-action',version:1});if(req.method!=='POST')return j({error:'Method tidak didukung.'},405);try{const c=await caller(req),b=await req.json(),fn=H[b?.function];if(!fn)return j({error:`Fungsi tidak diizinkan: ${b?.function||''}`},404);return j({result:await fn(Array.isArray(b.parameters)?b.parameters:[],c)})}catch(e){const message=e instanceof Error?e.message:String(e);const denied=/akses|token|hanya admin|assignment|ditolak/i.test(message);console.error(message);return j({error:message,result:{success:false,message}},denied?403:400)}});