import {CORS,json,text,sb,getCaller,applyRoleFilter,handlerError} from '../_shared/chattrx.ts';

const FIELDS=['jenis_transaksi','kategori','nama_item','keterangan','nominal','status_pembayaran'] as const;
const SYSTEM=`Kamu adalah asisten pencatatan transaksi keuangan bernama ChatTrx untuk organisasi SPPG/Yayasan. Pandu percakapan santai berbahasa Indonesia: jenis transaksi -> kategori -> nama item, keterangan, nominal -> konfirmasi natural -> foto nota -> status pembayaran -> jika lunas foto bukti pembayaran -> ringkasan akhir.
Jika user memberi beberapa informasi sekaligus, ekstrak semuanya dan jangan tanya ulang. Foto wajib dibaca nominal, tanggal, item, kejernihan dan indikasi manipulasi; tolak jika tidak meyakinkan atau berbeda signifikan. Jangan pernah melompati verifikasi foto. Balas ramah dan singkat. Keluarkan JSON saja sesuai schema yang diminta.`;
function nextState(d:any){if(!d.jenis_transaksi)return'jenis_transaksi';if(!d.kategori)return'kategori';if(!d.nama_item||!d.keterangan||!Number(d.nominal))return'detail';if(!d.detail_confirmed)return'konfirmasi_detail';if(!d.foto_nota_url||d.verifikasi_nota?.valid!==true)return'nota';if(!d.status_pembayaran)return'status_pembayaran';if(d.status_pembayaran==='sudah_dibayar'&&(!d.foto_bukti_bayar_url||d.verifikasi_bukti_bayar?.valid!==true))return'bukti_bayar';return'ringkasan';}
function chips(state:string,categories:any[]){if(state==='jenis_transaksi')return['Pemasukan','Pengeluaran'];if(state==='kategori')return categories.slice(0,6).map(x=>x.nama_kategori);if(state==='status_pembayaran')return['Sudah Dibayar/Lunas','Belum Dibayar'];return[]}
async function gemini(prompt:string,images:any[]){
  const key=Deno.env.get('GEMINI_API_KEY');if(!key)throw new Error('GEMINI_API_KEY belum dikonfigurasi.');
  const parts:any[]=[{text:prompt}];for(const im of images||[])if(im?.base64&&im?.mimeType)parts.push({inlineData:{mimeType:im.mimeType,data:String(im.base64).replace(/^data:[^,]+,/, '')}});
  const schema={type:'OBJECT',properties:{reply:{type:'STRING'},data:{type:'OBJECT',properties:{jenis_transaksi:{type:'STRING',nullable:true},kategori:{type:'STRING',nullable:true},nama_item:{type:'STRING',nullable:true},keterangan:{type:'STRING',nullable:true},nominal:{type:'NUMBER',nullable:true},status_pembayaran:{type:'STRING',nullable:true},detail_confirmed:{type:'BOOLEAN',nullable:true}}},image_type:{type:'STRING',nullable:true},verification:{type:'OBJECT',nullable:true,properties:{valid:{type:'BOOLEAN'},score:{type:'NUMBER'},reason:{type:'STRING'},nominal_terbaca:{type:'NUMBER',nullable:true},tanggal_terbaca:{type:'STRING',nullable:true},item_terbaca:{type:'STRING',nullable:true}}}},required:['reply','data']};
  const primary=Deno.env.get('GEMINI_MODEL')||'gemini-3.6-flash',models=[...new Set([primary,'gemini-3.5-flash-lite'])];
  const payload=JSON.stringify({systemInstruction:{parts:[{text:SYSTEM}]},contents:[{role:'user',parts}],generationConfig:{responseMimeType:'application/json',responseSchema:schema,temperature:.2}});let lastError='Gemini gagal memproses pesan.';
  for(const model of models)for(let attempt=0;attempt<2;attempt++){const url=`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:payload});const raw=await r.json();if(r.ok)return JSON.parse(raw?.candidates?.[0]?.content?.parts?.[0]?.text||'{}');lastError=raw?.error?.message||lastError;if(![429,503,504].includes(r.status))throw new Error(lastError);if(attempt===0)await new Promise(resolve=>setTimeout(resolve,450));}
  throw new Error('AI sedang sibuk. Silakan kirim ulang pesan beberapa saat lagi.');
}
async function storeImages(c:any,draftId:string,images:any[]){const out=[];for(let i=0;i<(images||[]).length;i++){const im=images[i];if(!im?.base64)continue;const ext=im.mimeType==='image/png'?'png':im.mimeType==='image/webp'?'webp':im.mimeType==='application/pdf'?'pdf':'jpg';const path=`${c.id}/${draftId}/${crypto.randomUUID()}.${ext}`;const bytes=Uint8Array.from(atob(String(im.base64).replace(/^data:[^,]+,/,'')),x=>x.charCodeAt(0));const u=await sb.storage.from('chattrx-evidence').upload(path,bytes,{contentType:im.mimeType,upsert:false});if(u.error)throw u.error;out.push(path)}return out}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'Method tidak didukung.'},405);try{
  const c=await getCaller(req),raw=await req.json(),body=Array.isArray(raw?.parameters)?raw.parameters[0]||{}:raw;let draft:any=null;
  if(body.draftId){let q:any=sb.from('CHATTRX_DRAFT').select('*').eq('draft_id',text(body.draftId)).maybeSingle();const r=await applyRoleFilter(q,c);if(r.error)throw r.error;draft=r.data;if(!draft)throw new Error('Draft tidak ditemukan atau akses ditolak.');}
  if(!draft){const r=await sb.from('CHATTRX_DRAFT').insert({user_id:c.id,sppg:c.sppg,yayasan:c.yayasan}).select('*').single();if(r.error)throw r.error;draft=r.data}
  let cq:any=sb.from('CHATTRX_KATEGORI').select('nama_kategori,jumlah_pemakaian').order('jumlah_pemakaian',{ascending:false}).limit(8);const cr=await applyRoleFilter(cq,c,{owner:'',sppg:'sppg',yayasan:'yayasan'});if(cr.error)throw cr.error;
  if(!text(body.message)&&!(body.images||[]).length){const state=nextState(draft);return json({result:{success:true,draftId:draft.draft_id,state,reply:'Transaksi ini Pemasukan atau Pengeluaran?',chips:chips(state,cr.data||[]),data:draft}})}
  const paths=await storeImages(c,draft.draft_id,body.images||[]);const ai=await gemini(`State saat ini: ${draft.current_state}. Data draft: ${JSON.stringify(draft)}. Pesan user: ${text(body.message)||'(lampiran saja)'}. ${paths.length?'Analisis lampiran sebagai nota atau bukti pembayaran sesuai state.':''}`,body.images||[]);
  const patch:any={};for(const f of FIELDS)if(ai.data?.[f]!==null&&ai.data?.[f]!==undefined&&text(ai.data[f]))patch[f]=f==='nominal'?Number(ai.data[f]):text(ai.data[f]).toLowerCase();
  if(ai.data?.detail_confirmed===true)patch.detail_confirmed=true;
  if(paths.length){const kind=ai.image_type==='payment'||draft.current_state==='bukti_bayar'?'payment':'nota';if(kind==='nota'){patch.foto_nota_url=paths[0];patch.verifikasi_nota=ai.verification||{valid:false,reason:'Foto belum dapat diverifikasi.'};if(paths[1]){patch.foto_bukti_bayar_url=paths[1];patch.verifikasi_bukti_bayar=ai.verification||{valid:false,reason:'Bukti pembayaran belum dapat diverifikasi.'}}}else{patch.foto_bukti_bayar_url=paths[0];patch.verifikasi_bukti_bayar=ai.verification||{valid:false,reason:'Foto belum dapat diverifikasi.'}}}
  const merged={...draft,...patch};patch.current_state=nextState(merged);patch.chat_history=[...(Array.isArray(draft.chat_history)?draft.chat_history:[]),{at:new Date().toISOString(),role:'user',text:text(body.message),attachments:paths},{at:new Date().toISOString(),role:'assistant',text:ai.reply,state:patch.current_state}];patch.updated_at=new Date().toISOString();
  const u=await sb.from('CHATTRX_DRAFT').update(patch).eq('draft_id',draft.draft_id).eq('user_id',draft.user_id).select('*').single();if(u.error)throw u.error;
  if(patch.kategori)await sb.from('CHATTRX_KATEGORI').upsert({nama_kategori:patch.kategori,jenis_transaksi:patch.jenis_transaksi||u.data.jenis_transaksi||'keduanya',sppg:u.data.sppg,yayasan:u.data.yayasan},{onConflict:'nama_kategori,jenis_transaksi,sppg,yayasan'});
  return json({result:{success:true,draftId:draft.draft_id,state:patch.current_state,reply:ai.reply,chips:chips(patch.current_state,cr.data||[]),data:u.data}})
}catch(e){return handlerError(e)}});
