import {CORS,json,text,sb,getCaller,applyRoleFilter,handlerError} from '../_shared/chattrx.ts';

const FIELDS=['jenis_transaksi','kategori','nama_item','keterangan','nominal','status_pembayaran','tanggal_transaksi','penerima'] as const;
const INCOME=['Anggaran Bahan Baku','Anggaran Sewa Mobil','Anggaran Insentif Fasilitas'] as const;
const EXPENSE=['Belanja Bahan Baku','Material Bangunan','Gas LPG','Sewa & Utilitas (AC/WIFI)','IPAL','Inventaris Kantor','Cetak & Promosi','Gaji/Upah Karyawan','Operasional Perjalanan','Konsumsi','Dana Talangan','Cicilan','Fee Yayasan','Administrasi & Lainnya'] as const;
const CATEGORIES=[...INCOME,...EXPENSE] as const;
const RECEIPT_REQUIRED=['Belanja Bahan Baku','Material Bangunan','Gas LPG','Sewa & Utilitas (AC/WIFI)','IPAL','Inventaris Kantor','Cetak & Promosi','Operasional Perjalanan','Konsumsi','Administrasi & Lainnya'];
const norm=(v:unknown)=>text(v).replace(/\s+/g,' ').toLocaleLowerCase('id-ID');
const category=(v:unknown)=>CATEGORIES.find(x=>norm(x)===norm(v))||'';
const categoryType=(v:unknown)=>INCOME.includes(v as any)?'pemasukan':EXPENSE.includes(v as any)?'pengeluaran':'';

const SYSTEM=`Kamu adalah asisten akuntansi AI untuk ChatTransaksi SPPG/Yayasan. Tujuanmu adalah menghasilkan pencatatan yang akurat dan siap dikonfirmasi dengan usaha minimum dari pengguna. Kamu bukan bot formulir, auditor yang mencari-cari alasan menolak, atau petugas dukungan UI.

Cara bekerja dan berkomunikasi:
- Baca pesan, draft, dan seluruh lampiran sebagai satu konteks. Kerjakan sebanyak mungkin sebelum bertanya.
- Bedakan sumber keputusan dalam basis: fakta yang terbaca dari dokumen, informasi yang dinyatakan pengguna, dan rekomendasi akuntansi yang kamu buat.
- Jangan menanyakan ulang data yang sudah jelas. Jangan meminta pengguna memilih jenis atau kategori jika keduanya dapat disimpulkan.
- Ajukan paling banyak satu pertanyaan: pilih hanya kekurangan atau konflik yang paling menentukan. clarifying_question harus null bila pencatatan sudah dapat diselesaikan.
- Balas seperti rekan kerja yang cermat: hangat, singkat, konkret, dan percaya diri secara proporsional. Hindari bahasa prosedural seperti "isi field", "tahap berikutnya", atau saran memuat ulang halaman.
- Jangan mengarang fakta. Data yang tidak terbukti harus null. Rekomendasi seperti kategori, nama transaksi, dan catatan akuntansi boleh dirumuskan dari fakta yang terverifikasi.
- Jika ada konflik material, jelaskan kedua nilai dan tanyakan mana yang digunakan; jangan memilih diam-diam.
- Jika lengkap, nyatakan apa yang berhasil dibaca, kategori yang direkomendasikan, dan bahwa ringkasan siap diperiksa. Jangan menuliskan ulang tabel ringkasan secara panjang di reply.

Penalaran akuntansi:
- Kebutuhan dokumen mengikuti substansi transaksi. Nota wajib untuk pembelian barang/jasa, tetapi tidak wajib untuk Gaji/Upah Karyawan, Dana Talangan, Cicilan, Fee Yayasan, atau pemasukan.
- Bukti transfer valid berarti transaksi sudah dibayar. Ambil tujuan transfer sebagai penerima, nominal transfer sebagai nominal, dan tanggal/waktu bukti sebagai tanggal_transaksi.
- Untuk gaji, bukti transfer adalah dokumen utama dan nota tidak diperlukan. Bentuk nama_item "Gaji [penerima]" dan keterangan singkat "Pembayaran gaji kepada [penerima]". Periode hanya boleh disebut bila terlihat atau ditulis pengguna.
- Invoice/tagihan digital dapat berfungsi sebagai nota. Satu dokumen boleh menjadi nota sekaligus bukti pembayaran bila isinya mendukung atau pengguna menetapkannya demikian.
- Informasi opsional tidak boleh menghalangi konfirmasi. Bila hanya data opsional yang tidak tersedia, lanjutkan dengan rekomendasi tanpa menanyakannya.

Kategori resmi, harus persis salah satu nilai berikut:
Pemasukan: ${INCOME.join('; ')}.
Pengeluaran: ${EXPENSE.join('; ')}.
Tentukan jenis_transaksi berdasarkan kategori. Jika belum cukup bukti, kategori harus null; boleh sebutkan dugaan di reply tanpa menyimpannya sebagai fakta.

Lampiran:
- Keluarkan tepat satu attachment_review per file sesuai index/urutan, termasuk file buram, duplikat, atau tidak relevan.
- Bedakan nota/invoice dari bukti pembayaran/transfer. Gunakan both hanya bila satu file benar-benar membuktikan keduanya.
- Jika pengguna secara eksplisit menyebut fungsi sebuah lampiran (misalnya "ini nota"), hormati keterangan itu selama isi visual tidak jelas bertentangan. Perintah pengguna untuk memakai dokumen yang sama sebagai nota dan bukti pembayaran harus dipahami sebagai keputusan pencatatan, bukan permintaan lampiran baru.
- valid berarti dokumen cukup terbaca dan konsisten untuk fungsinya. Jangan menyatakan manipulasi sebagai kepastian; tulis indikator konkret di warnings.
- Bandingkan nominal, tanggal, dan item dari semua sumber dan masukkan perbedaan ke conflicts.
- Simpan tanggal dan waktu dokumen sebagai ISO 8601 pada tanggal_transaksi. Untuk bukti transfer, ambil nama tujuan/penerima, bukan nama pengirim, kecuali konteks menyatakan sebaliknya.

Gunakan intent=correct hanya untuk koreksi eksplisit. missing_fields hanya berisi data wajib yang benar-benar menghalangi penyimpanan dan harus mengikuti kebutuhan dokumen per kategori. Keluarkan JSON saja.`;

function requiresReceipt(d:any){return RECEIPT_REQUIRED.includes(text(d.kategori));}
function evidenceReuseTarget(v:unknown,state:string){const s=text(v);if(!/(?:jadikan|gunakan|pakai|anggap|sebagai)/i.test(s))return'';const nota=/(?:foto|gambar|dokumen|lampiran|bukti).{0,45}(?:sebagai|jadi|jadikan)?.{0,20}\bnota\b|\bnota\b.{0,35}(?:foto|gambar|dokumen|lampiran|bukti)/i.test(s),payment=/(?:foto|gambar|dokumen|lampiran|nota).{0,45}(?:sebagai|jadi|jadikan)?.{0,20}(?:bukti|pembayaran|transaksi)|(?:bukti pembayaran|bukti transaksi).{0,35}(?:foto|gambar|dokumen|lampiran|nota)/i.test(s);if(nota&&payment)return'both';if(nota)return'nota';if(payment)return'payment';if(/foto\s*(?:di\s*)?(?:atas|tadi|sebelumnya)|dokumen\s*(?:ini|tadi)/i.test(s))return state==='nota'?'nota':state==='bukti_bayar'?'payment':'';return'';}
function nextState(d:any){if(!d.jenis_transaksi)return'jenis_transaksi';if(!d.kategori)return'kategori';if(!d.nama_item||!d.keterangan||!Number(d.nominal)||!d.tanggal_transaksi||(d.kategori==='Gaji/Upah Karyawan'&&!d.penerima))return'detail';if(!d.status_pembayaran)return'status_pembayaran';if(requiresReceipt(d)&&(!d.foto_nota_url||d.verifikasi_nota?.valid!==true))return'nota';if(d.status_pembayaran==='sudah_dibayar'&&(!d.foto_bukti_bayar_url||d.verifikasi_bukti_bayar?.valid!==true))return'bukti_bayar';return'ringkasan';}
function normalizedField(field:string,value:unknown){const v=norm(value);if(field==='jenis_transaksi')return v==='pengeluaran'?'pengeluaran':v==='pemasukan'?'pemasukan':'';if(field==='status_pembayaran')return v.includes('belum')?'belum_dibayar':(/sudah|lunas/.test(v)?'sudah_dibayar':'');if(field==='kategori')return category(value);return field==='nominal'?Number(value):text(value);}
function oneQuestion(v:unknown){let seen=false;return text(v).replace(/\?/g,()=>seen?'.':(seen=true,'?'));}
function chips(state:string,rows:any[]){if(state==='jenis_transaksi')return['Pemasukan','Pengeluaran'];if(state==='kategori'){const usage=new Map(rows.map(x=>[norm(x.nama_kategori),Number(x.jumlah_pemakaian)||0]));return [...CATEGORIES].sort((a,b)=>(usage.get(norm(b))||0)-(usage.get(norm(a))||0)).slice(0,6)}if(state==='konfirmasi_detail')return['Ya, sudah benar'];if(state==='status_pembayaran')return['Sudah Dibayar/Lunas','Belum Dibayar'];return[];}
function fallbackReply(state:string,d:any){if(state==='jenis_transaksi'||state==='kategori')return'Ceritakan transaksinya atau kirim dokumen yang tersedia—saya akan membaca dan mengklasifikasikannya.';if(state==='detail'){if(!Number(d.nominal))return'Nominal transaksi belum terlihat. Berapa nominal yang ingin dicatat?';if(!d.tanggal_transaksi)return'Tanggal transaksi belum terlihat. Kapan transaksi ini dilakukan?';if(d.kategori==='Gaji/Upah Karyawan'&&!d.penerima)return'Nama penerima gaji belum terlihat. Siapa penerimanya?';if(!d.nama_item)return'Transaksi ini belum memiliki nama yang cukup jelas. Apa nama transaksi yang ingin digunakan?';return'Saya belum memiliki keterangan yang cukup untuk pencatatan ini. Transaksi ini untuk keperluan apa?';}if(state==='nota')return'Saya sudah memahami transaksinya, tetapi dokumen pembelian belum cukup terbaca sebagai nota. Dapatkah Anda mengirim bagian nota yang menampilkan rincian dan nominal?';if(state==='status_pembayaran')return'Data transaksi sudah terbaca. Apakah transaksi ini sudah dibayar atau masih belum dibayar?';if(state==='bukti_bayar')return'Pencatatannya sudah siap, tetapi status lunas memerlukan bukti pembayaran. Kirim bukti yang menampilkan nominal dan waktu transaksi.';return'Semua data wajib sudah lengkap. Periksa rekomendasi di bawah, lalu pilih Konfirmasi & Simpan atau ketik koreksi Anda.';}
function outputText(raw:any){if(text(raw?.output_text))return text(raw.output_text);for(const item of raw?.output||[])for(const part of item?.content||[])if(part?.type==='output_text'&&text(part.text))return text(part.text);return'';}
function attachmentInput(im:any,index:number){if(!im?.base64||!im?.mimeType)return null;const mime=norm(im.mimeType),raw=String(im.base64),url=raw.startsWith('data:')?raw:`data:${mime};base64,${raw}`;return mime==='application/pdf'?{type:'input_file',filename:text(im.name)||`chattrx-${index+1}.pdf`,file_data:url}:{type:'input_image',image_url:url,detail:'high'};}

async function askOpenAI(prompt:string,images:any[]){
  const key=Deno.env.get('OPENAI_API_KEY');if(!key)throw new Error('Layanan AI ChatTrx belum siap. Hubungi administrator untuk memasang secret OPENAI_API_KEY pada project Supabase.');
  const content:any[]=[{type:'input_text',text:prompt}];images.forEach((im,i)=>{const item=attachmentInput(im,i);if(item)content.push(item)});
  const ns={type:['string','null']},review={type:'object',additionalProperties:false,properties:{index:{type:'integer'},kind:{type:'string',enum:['nota','payment','both','unknown']},valid:{type:'boolean'},confidence:{type:'number',minimum:0,maximum:1},reason:{type:'string'},nominal:{type:['number','null']},tanggal:ns,waktu:ns,merchant_or_sender:ns,penerima:ns,reference_number:ns,items:{type:'array',items:{type:'string'}},warnings:{type:'array',items:{type:'string'}}},required:['index','kind','valid','confidence','reason','nominal','tanggal','waktu','merchant_or_sender','penerima','reference_number','items','warnings']};
  const conflict={type:'object',additionalProperties:false,properties:{field:{type:'string'},draft_value:ns,incoming_value:ns,source:{type:'string'},question:{type:'string'}},required:['field','draft_value','incoming_value','source','question']};
  const basis={type:'object',additionalProperties:false,properties:{from_document:{type:'array',items:{type:'string'}},from_user:{type:'array',items:{type:'string'}},recommended:{type:'array',items:{type:'string'}}},required:['from_document','from_user','recommended']};
  const schema={type:'object',additionalProperties:false,properties:{reply:{type:'string'},intent:{type:'string',enum:['provide_data','correct','confirm','question']},data:{type:'object',additionalProperties:false,properties:{jenis_transaksi:{anyOf:[{type:'string',enum:['pemasukan','pengeluaran']},{type:'null'}]},kategori:{anyOf:[{type:'string',enum:[...CATEGORIES]},{type:'null'}]},nama_item:ns,keterangan:ns,nominal:{type:['number','null']},status_pembayaran:{anyOf:[{type:'string',enum:['sudah_dibayar','belum_dibayar']},{type:'null'}]},tanggal_transaksi:ns,penerima:ns,detail_confirmed:{type:['boolean','null']}},required:['jenis_transaksi','kategori','nama_item','keterangan','nominal','status_pembayaran','tanggal_transaksi','penerima','detail_confirmed']},basis,clarifying_question:ns,missing_fields:{type:'array',items:{type:'string',enum:['jenis_transaksi','kategori','nama_item','keterangan','nominal','tanggal_transaksi','penerima','foto_nota','status_pembayaran','foto_bukti_bayar']}},conflicts:{type:'array',items:conflict},attachment_reviews:{type:'array',items:review}},required:['reply','intent','data','basis','clarifying_question','missing_fields','conflicts','attachment_reviews']};
  const payload={model:Deno.env.get('OPENAI_MODEL')||'gpt-5.6-terra',store:false,reasoning:{effort:'low'},instructions:SYSTEM,input:[{role:'user',content}],text:{format:{type:'json_schema',name:'chattrx_transaction_review',strict:true,schema}},max_output_tokens:1800};
  let last='ChatGPT gagal memproses pesan.';for(let attempt=0;attempt<2;attempt++){const res=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),raw=await res.json().catch(()=>({}));if(res.ok){const value=outputText(raw);if(!value)throw new Error('ChatGPT tidak mengembalikan data yang dapat diproses.');try{return JSON.parse(value)}catch{throw new Error('Respons ChatGPT tidak valid.')}}last=text(raw?.error?.message)||last;if(![429,500,502,503,504].includes(res.status))throw new Error(last);if(!attempt)await new Promise(r=>setTimeout(r,500));}throw new Error('ChatGPT sedang sibuk. Silakan kirim ulang beberapa saat lagi.');
}
async function storeFiles(c:any,draftId:string,images:any[]){const paths:string[]=[];for(const im of images){const mime=norm(im.mimeType),ext=mime==='image/png'?'png':mime==='image/webp'?'webp':mime==='application/pdf'?'pdf':'jpg',path=`${c.id}/${draftId}/${crypto.randomUUID()}.${ext}`,bytes=Uint8Array.from(atob(String(im.base64).replace(/^data:[^,]+,/,'')),x=>x.charCodeAt(0)),up=await sb.storage.from('chattrx-evidence').upload(path,bytes,{contentType:mime,upsert:false});if(up.error)throw up.error;paths.push(path)}return paths;}
function verification(reviews:any[],paths:string[],kinds:string[]){const files=reviews.map((x:any,i:number)=>({...x,path:paths[i]||null})).filter((x:any)=>x.path&&kinds.includes(x.kind));return{valid:files.some((x:any)=>x.valid===true),reason:files.map((x:any)=>x.reason).filter(Boolean).join(' | ')||'Tidak ada lampiran yang cocok.',files};}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'Method tidak didukung.'},405);try{
  const caller=await getCaller(req),raw=await req.json(),body=Array.isArray(raw?.parameters)?raw.parameters[0]||{}:raw;let draft:any=null;
  if(body.draftId){let q:any=sb.from('CHATTRX_DRAFT').select('*').eq('draft_id',text(body.draftId)).maybeSingle();const found=await applyRoleFilter(q,caller);if(found.error)throw found.error;draft=found.data;if(!draft)throw new Error('Draft tidak ditemukan atau akses ditolak.');}
  if(!draft&&body.resume===true){const found=await sb.from('CHATTRX_DRAFT').select('*').eq('user_id',caller.id).eq('status','in_progress').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(found.error)throw found.error;draft=found.data;}
  if(!draft){const made=await sb.from('CHATTRX_DRAFT').insert({user_id:caller.id,sppg:caller.sppg,yayasan:caller.yayasan}).select('*').single();if(made.error)throw made.error;draft=made.data;}
  let cq:any=sb.from('CHATTRX_KATEGORI').select('nama_kategori,jumlah_pemakaian').order('jumlah_pemakaian',{ascending:false}).limit(50);const categories=await applyRoleFilter(cq,caller,{owner:'',sppg:'sppg',yayasan:'yayasan'});if(categories.error)throw categories.error;
  const images=(body.images||[]).filter((x:any)=>x?.base64&&x?.mimeType);if(!text(body.message)&&!images.length){const state=nextState(draft);return json({result:{success:true,draftId:draft.draft_id,state,reply:fallbackReply(state,draft),chips:chips(state,categories.data||[]),data:draft}});}
  const paths=await storeFiles(caller,draft.draft_id,images),context={current_state:draft.current_state,draft:{jenis_transaksi:draft.jenis_transaksi,kategori:draft.kategori,nama_item:draft.nama_item,keterangan:draft.keterangan,nominal:draft.nominal,status_pembayaran:draft.status_pembayaran,tanggal_transaksi:draft.tanggal_transaksi,penerima:draft.penerima},message:text(body.message)||'(hanya lampiran)',attachments:images.map((x:any,i:number)=>({index:i,name:text(x.name)||`lampiran-${i+1}`,mime_type:text(x.mimeType)}))},ai=await askOpenAI(`Konteks giliran:\n${JSON.stringify(context)}`,images);
  if(!Array.isArray(ai.attachment_reviews)||ai.attachment_reviews.length!==images.length||ai.attachment_reviews.some((x:any,i:number)=>x.index!==i))throw new Error('ChatGPT belum berhasil mereview setiap lampiran. Silakan kirim ulang.');
  const patch:any={},replace=ai.intent==='correct';for(const field of FIELDS){const incoming=ai.data?.[field];if(incoming===null||incoming===undefined||!text(incoming))continue;const value=normalizedField(field,incoming);if(value===''||value===null||(field==='nominal'&&!Number.isFinite(value)))continue;if(!draft[field]||replace||norm(draft[field])===norm(value))patch[field]=value;}
  if(patch.kategori)patch.jenis_transaksi=categoryType(patch.kategori);
  if(paths.length){const note=verification(ai.attachment_reviews,paths,['nota','both']),pay=verification(ai.attachment_reviews,paths,['payment','both']),ni=ai.attachment_reviews.findIndex((x:any)=>['nota','both'].includes(x.kind)&&x.valid),pi=ai.attachment_reviews.findIndex((x:any)=>['payment','both'].includes(x.kind)&&x.valid);if(note.files.length&&(note.valid||draft.verifikasi_nota?.valid!==true)){patch.verifikasi_nota=note;if(ni>=0)patch.foto_nota_url=paths[ni];}if(pay.files.length&&(pay.valid||draft.verifikasi_bukti_bayar?.valid!==true)){patch.verifikasi_bukti_bayar=pay;if(pi>=0)patch.foto_bukti_bayar_url=paths[pi];}}
  const reuseTarget=evidenceReuseTarget(body.message,draft.current_state);if(reuseTarget){const available={...draft,...patch};if((reuseTarget==='payment'||reuseTarget==='both')&&available.foto_nota_url&&available.verifikasi_nota?.valid===true){patch.foto_bukti_bayar_url=available.foto_nota_url;patch.verifikasi_bukti_bayar={...available.verifikasi_nota,reused_as:'payment',user_designated:true};}if((reuseTarget==='nota'||reuseTarget==='both')&&available.foto_bukti_bayar_url&&available.verifikasi_bukti_bayar?.valid===true){patch.foto_nota_url=available.foto_bukti_bayar_url;patch.verifikasi_nota={...available.verifikasi_bukti_bayar,reused_as:'nota',user_designated:true};}}
  let prepared={...draft,...patch};if(prepared.verifikasi_bukti_bayar?.valid===true)patch.status_pembayaran='sudah_dibayar';prepared={...prepared,...patch};if(prepared.kategori==='Gaji/Upah Karyawan'&&prepared.penerima){if(!prepared.nama_item)patch.nama_item=`Gaji ${prepared.penerima}`;if(!prepared.keterangan)patch.keterangan=`Pembayaran gaji kepada ${prepared.penerima}`;}
  const merged={...draft,...patch},hasConflict=Array.isArray(ai.conflicts)&&ai.conflicts.length>0&&ai.intent!=='correct';patch.current_state=hasConflict?'detail':nextState(merged);const staleEvidenceRequest=(patch.current_state!=='nota'&&/\bnota\b/i.test(text(ai.reply))&&/(kirim|unggah|lampir|perlu|butuh|memerlukan)/i.test(text(ai.reply)))||(patch.current_state!=='bukti_bayar'&&/(bukti pembayaran|bukti transfer)/i.test(text(ai.reply))&&/(kirim|unggah|lampir|perlu|butuh|memerlukan)/i.test(text(ai.reply))),prematureConfirmation=patch.current_state!=='ringkasan'&&/(data.{0,20}(?:sudah )?lengkap|siap.{0,30}(?:konfirmasi|simpan)|klik.{0,20}konfirmasi)/i.test(text(ai.reply)),preferredReply=hasConflict&&text(ai.clarifying_question)?text(ai.clarifying_question):text(ai.reply);const reply=oneQuestion((staleEvidenceRequest||prematureConfirmation)?fallbackReply(patch.current_state,merged):(preferredReply||fallbackReply(patch.current_state,merged))),reviews=ai.attachment_reviews.map((x:any,i:number)=>({...x,path:paths[i]||null}));patch.chat_history=[...(Array.isArray(draft.chat_history)?draft.chat_history:[]),{at:new Date().toISOString(),role:'user',text:text(body.message),attachments:paths},{at:new Date().toISOString(),role:'assistant',text:reply,state:patch.current_state,basis:ai.basis||null,missing_fields:ai.missing_fields||[],conflicts:ai.conflicts||[],attachment_reviews:reviews}];patch.updated_at=new Date().toISOString();
  const updated=await sb.from('CHATTRX_DRAFT').update(patch).eq('draft_id',draft.draft_id).eq('user_id',draft.user_id).select('*').single();if(updated.error)throw updated.error;if(patch.kategori)await sb.from('CHATTRX_KATEGORI').upsert({nama_kategori:patch.kategori,jenis_transaksi:patch.jenis_transaksi||updated.data.jenis_transaksi,sppg:updated.data.sppg,yayasan:updated.data.yayasan},{onConflict:'nama_kategori,jenis_transaksi,sppg,yayasan'});
  return json({result:{success:true,draftId:draft.draft_id,state:patch.current_state,reply,chips:chips(patch.current_state,categories.data||[]),data:updated.data,review:{basis:ai.basis||null,missingFields:ai.missing_fields||[],conflicts:ai.conflicts||[],attachments:reviews}}});
}catch(e){return handlerError(e);}});
